// svelte/MatchCard.svelte
<script lang="ts">
  /**
   * DSS MatchCard · Svelte 5
   * --------------------------------------------------------------
   * Drei Spielzustände, eine Kartengrammatik. Nutzt nur Klassen aus css/components.css.
   *
   *   scheduled — Datum/Uhrzeit, Halle, Teams
   *   live      — Spielstand, Spielabschnitt + Uhr, Puls
   *   finished  — Endstand, Sieger/Verlierer
   *
   * Mit `href` ist die Karte ein Link, mit `onclick` ein Button, sonst ein div.
   *
   * `names`: "full" (Standard) oder "short" (Kurzname, falls vorhanden); bis 640 px Breite erscheint
   * der Kurzname automatisch (CSS, Viewport-Regel). `logos`: Logo bzw. Initialen vor dem Namen (Standard aus).
   *
   * Spielabschnitt (nur live): `period` (ab 1) mit `periods` (4 Viertel, Standard, oder 8 Achtel) ergibt „3. Viertel“,
   * „5. Achtel“, „Verlängerung“ (js/periods.js). `quarter` ist veraltet und bleibt als Alias: Ohne `period` wird der
   * Text unverändert angezeigt.
   */
  import { initials, shortName } from '../js/schedule.js';
  import { resolvePeriod } from '../js/periods.js';
  type State = 'scheduled' | 'live' | 'finished';
  type Team = { name: string; short?: string; logo?: string; color?: 'heim' | 'gast'; score?: number };
  type Names = 'full' | 'short';

  let {
    state = 'scheduled',
    league = '',
    matchday = '',
    date = '',
    time = '',
    venue = '',
    heim,
    gast,
    names = 'full',
    logos = false,
    period = undefined,
    periods = 4,
    quarter = '',
    clock = '',
    href = undefined,
    onclick = undefined,
  }: {
    state?: State;
    league?: string;
    matchday?: string;
    date?: string;
    time?: string;
    venue?: string;
    heim: Team;
    gast: Team;
    names?: Names;
    logos?: boolean;
    period?: number;
    periods?: 4 | 8;
    /** @deprecated Stattdessen `period`; ohne `period` wird der Text unverändert angezeigt. */
    quarter?: string;
    clock?: string;
    href?: string;
    onclick?: () => void;
  } = $props();

  let heimWin = $derived(state === 'finished' && (heim.score ?? 0) > (gast.score ?? 0));
  let gastWin = $derived(state === 'finished' && (gast.score ?? 0) > (heim.score ?? 0));
  const tag = $derived(href ? 'a' : onclick ? 'button' : 'div');
  const liveText = $derived([resolvePeriod({ period, periods, quarter }).label, clock].filter(Boolean).join(' '));
</script>

{#snippet teamBlock(t: Team)}
  {#if logos}<span class="dss-team-logo" class:dss-team-logo--initials={!t.logo} aria-hidden="true">{#if t.logo}<img src={t.logo} alt="" loading="lazy" />{:else}{initials(t.name, 2)}{/if}</span>{/if}
  {#if shortName(t)}<span class="dss-match-name dss-team-name" class:dss-team-name--short={names === 'short'}><span class="dss-name-full">{t.name}</span><span class="dss-name-short" aria-hidden="true" title={t.name}>{shortName(t)}</span></span>{:else}<span class="dss-match-name">{t.name}</span>{/if}
{/snippet}

<!-- Der Handler hängt nur an <a>/<button> (nie am <div>); Svelte kann das bei svelte:element nicht erkennen. -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<svelte:element
  this={tag}
  class={`dss-match dss-match--${state}${logos ? ' dss-match--logos' : ''}`}
  href={tag === 'a' ? href : undefined}
  type={tag === 'button' ? 'button' : undefined}
  onclick={tag === 'div' ? undefined : onclick}
>
  <span class="dss-match-head">
    <span class="dss-match-league">
      {#if league}<span>{league}</span>{/if}
      {#if matchday}<span class="dss-match-muted">· {matchday}</span>{/if}
    </span>
    {#if state === 'live'}
      <span class="dss-match-live"><span class="dss-match-pulse" aria-hidden="true"></span> Live · {liveText}</span>
    {:else if state === 'finished'}
      <span class="dss-match-final">Endstand</span>
    {:else if date}
      <span class="dss-match-when">{date}{time ? ` · ${time}` : ''}</span>
    {/if}
  </span>

  <span class="dss-match-body">
    <span class={`dss-match-team ${gastWin ? 'is-loser' : ''}`}>
      <span class="dss-match-dot" aria-hidden="true"></span>
      {@render teamBlock(heim)}
      {#if state !== 'scheduled' && heim.score !== undefined}<span class="dss-match-score">{heim.score}</span>{/if}
    </span>
    <span class={`dss-match-team dss-match-team--gast ${heimWin ? 'is-loser' : ''}`}>
      <span class="dss-match-dot" aria-hidden="true"></span>
      {@render teamBlock(gast)}
      {#if state !== 'scheduled' && gast.score !== undefined}<span class="dss-match-score">{gast.score}</span>{/if}
    </span>
  </span>

  {#if venue}
    <span class="dss-match-foot"><span>{venue}</span></span>
  {/if}
</svelte:element>

// react/MatchCard.tsx
import type { MouseEventHandler } from 'react';
import { cn } from './cn';
import { shortName } from '../js/schedule.js';
import { resolvePeriod } from '../js/periods.js';
import { TeamLogo } from './ScheduleParts';

export type MatchState = 'scheduled' | 'live' | 'finished';

export type MatchNames = 'full' | 'short';

export interface MatchTeam {
  name: string;
  /** Kurzname (z. B. "Hawks"): Anzeige bei `names="short"` und automatisch bis 640 px Breite. */
  short?: string;
  /** Logo-URL; ohne Logo erscheinen bei `logos` die Initialen. */
  logo?: string;
  score?: number;
}

export interface MatchCardProps {
  state?: MatchState;
  league?: string;
  matchday?: string;
  date?: string;
  time?: string;
  venue?: string;
  heim: MatchTeam;
  gast: MatchTeam;
  /** `short` zeigt den Kurzname, falls vorhanden; bis 640 px Breite erscheint er automatisch (CSS). Standard: `full`. */
  names?: MatchNames;
  /** Logo bzw. Initialen vor dem Teamnamen. Standard: aus. */
  logos?: boolean;
  /** Nur bei `live`: Spielabschnitt ab 1 (mit `periods`: „3. Viertel“, „5. Achtel“, „Verlängerung“). */
  period?: number;
  /** 4 Viertel (Standard) oder 8 Achtel (Mini-Basketball). */
  periods?: 4 | 8;
  /** @deprecated Stattdessen `period`; ohne `period` wird der Text unverändert angezeigt. */
  quarter?: string;
  /** Nur bei `live`: Spieluhr. */
  clock?: string;
  /** Mit `href` wird die Karte ein Link, mit `onClick` ein Button, sonst ein div. */
  href?: string;
  onClick?: MouseEventHandler<HTMLElement>;
  className?: string;
}

/** Spielkarte in drei Zuständen: angesetzt, live, beendet (Sieger/Verlierer). */
export function MatchCard({
  state = 'scheduled',
  league,
  matchday,
  date,
  time,
  venue,
  heim,
  gast,
  names = 'full',
  logos = false,
  period,
  periods = 4,
  quarter = '',
  clock = '',
  href,
  onClick,
  className,
}: MatchCardProps) {
  const heimWin = state === 'finished' && (heim.score ?? 0) > (gast.score ?? 0);
  const gastWin = state === 'finished' && (gast.score ?? 0) > (heim.score ?? 0);
  const showScore = state !== 'scheduled';
  const liveText = [resolvePeriod({ period, periods, quarter }).label, clock].filter(Boolean).join(' ');

  const teamBlock = (team: MatchTeam) => {
    const short = shortName(team);
    return (
      <>
        {logos ? <TeamLogo name={team.name} logo={team.logo} /> : null}
        {short ? (
          <span className={cn('dss-match-name', 'dss-team-name', names === 'short' && 'dss-team-name--short')}>
            <span className="dss-name-full">{team.name}</span>
            <span className="dss-name-short" aria-hidden="true" title={team.name}>
              {short}
            </span>
          </span>
        ) : (
          <span className="dss-match-name">{team.name}</span>
        )}
      </>
    );
  };

  const body = (
    <>
      <span className="dss-match-head">
        <span className="dss-match-league">
          {league ? <span>{league}</span> : null}
          {matchday ? <span className="dss-match-muted">· {matchday}</span> : null}
        </span>
        {state === 'live' ? (
          <span className="dss-match-live">
            <span className="dss-match-pulse" aria-hidden="true" /> Live · {liveText}
          </span>
        ) : state === 'finished' ? (
          <span className="dss-match-final">Endstand</span>
        ) : date ? (
          <span className="dss-match-when">
            {date}
            {time ? ` · ${time}` : ''}
          </span>
        ) : null}
      </span>
      <span className="dss-match-body">
        <span className={cn('dss-match-team', gastWin && 'is-loser')}>
          <span className="dss-match-dot" aria-hidden="true" />
          {teamBlock(heim)}
          {showScore && heim.score !== undefined ? <span className="dss-match-score">{heim.score}</span> : null}
        </span>
        <span className={cn('dss-match-team', 'dss-match-team--gast', heimWin && 'is-loser')}>
          <span className="dss-match-dot" aria-hidden="true" />
          {teamBlock(gast)}
          {showScore && gast.score !== undefined ? <span className="dss-match-score">{gast.score}</span> : null}
        </span>
      </span>
      {venue ? (
        <span className="dss-match-foot">
          <span>{venue}</span>
        </span>
      ) : null}
    </>
  );

  const cls = cn('dss-match', `dss-match--${state}`, logos && 'dss-match--logos', className);
  if (href) {
    return (
      <a className={cls} href={href} onClick={onClick}>
        {body}
      </a>
    );
  }
  if (onClick) {
    return (
      <button type="button" className={cls} onClick={onClick}>
        {body}
      </button>
    );
  }
  return <div className={cls}>{body}</div>;
}
