// svelte/PlayerCard.svelte
<script lang="ts">
  import type { HeadingTag } from '../js/heading.js';
  import { useHeadingTag } from './heading-context.js';
  /**
   * DSS PlayerCard · Svelte 5
   * --------------------------------------------------------------
   * Drei Maßstäbe derselben Spielerprimitive. Nutzt nur Klassen aus css/components.css
   * (`.dss-tn`/`.dss-pos` teilt sie mit der Table).
   *
   *   compact  — Listenzeile (Roster / Bank); mit `onclick` ein Button, sonst ein div
   *   standard — Karte mit Kopf + 4 Kennzahlen
   *   hero     — dunkle Großkarte mit großer Trikotnummer + 4 Kennzahlen
   *
   * `photo` (URL) ersetzt die Trikotmarke durch ein Foto; die Trikotnummer bleibt als Badge (hero: Porträtfläche links).
   * `photoAlt` ist standardmäßig leer (dekorativ, der Name steht daneben). Ohne `photo`, mit leerem `photo` oder bei
   * Ladefehler bleibt die Trikotmarke.
   */
  type Size = 'compact' | 'standard' | 'hero';
  type Stat = { label: string; value: string | number; accent?: boolean };

  let {
    size = 'standard',
    jersey,
    name,
    position = '',
    team = 'heim',
    captain = false,
    age = '',
    height_cm = '',
    role = '',
    vitals = [],
    stat = null,
    statLabel = '',
    onclick = undefined,
    titleAs = undefined,
    photo = '',
    photoAlt = '',
  }: {
    size?: Size;
    jersey: string | number;
    name: string;
    position?: string;
    team?: 'heim' | 'gast';
    captain?: boolean;
    age?: string;
    height_cm?: string;
    role?: string;
    vitals?: Stat[];
    stat?: string | number | null;
    statLabel?: string;
    onclick?: () => void;
    /** Überschriftenebene, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
    titleAs?: HeadingTag;
    photo?: string;
    photoAlt?: string;
  } = $props();

  const heading = useHeadingTag(() => titleAs);

  const posClass = $derived(position ? `dss-pos ${position.toLowerCase()}` : '');

  // Eine URL, die nicht lädt, wird gemerkt: dann erscheint wieder die Trikotmarke (kein kaputtes Bildsymbol)
  let failedUrl = $state('');
  const showPhoto = $derived(Boolean(photo) && photo !== failedUrl);
  const imgSize = $derived(size === 'compact' ? 32 : size === 'standard' ? 64 : 200);
</script>

{#snippet roleLine()}
  <div class="dss-pc-role">
    {#if position}<span class={posClass}>{position}</span>{/if}
    {#if captain}<span class="dss-pc-cap">Kapitän</span>{/if}
    {#if age}<span>{age}</span>{/if}
    {#if height_cm}<span>{height_cm} cm</span>{/if}
  </div>
{/snippet}

{#snippet vitalsGrid()}
  {#if vitals.length}
    <div class="dss-pc-vitals">
      {#each vitals as v (v.label)}
        <div>
          <div class={`dss-pc-v ${v.accent ? 'dss-pc-v--amber' : ''}`}>{v.value}</div>
          <div class="dss-pc-l">{v.label}</div>
        </div>
      {/each}
    </div>
  {/if}
{/snippet}

{#snippet photoImg()}
  <img class="dss-pc-img" src={photo} alt={photoAlt} width={imgSize} height={imgSize} loading="lazy" decoding="async" onerror={() => (failedUrl = photo)} />
{/snippet}

{#snippet compactBody()}
  {#if showPhoto}
    <span class="dss-pc-av">{@render photoImg()}<span class={`dss-tn dss-tn--badge ${team} ${captain ? 'captain' : ''}`}>{jersey}</span></span>
  {:else}
    <span class={`dss-tn ${team} small ${captain ? 'captain' : ''}`}>{jersey}</span>
  {/if}
  <span class="dss-pc-who">
    <span class="dss-pc-name">{name}{captain ? ' (C)' : ''}</span>
    {#if role || position}
      <span class="dss-pc-meta">{position}{role ? ` · ${role}` : ''}</span>
    {/if}
  </span>
  <!-- Pill nur visuell: die Position steht schon in der Meta-Zeile. Leeres span = Platzhalter für die Grid-Spalte. -->
  {#if position}<span class={posClass} aria-hidden="true">{position}</span>{:else}<span></span>{/if}
  {#if stat !== null}
    <span class="dss-pc-stat">
      {stat}
      {#if statLabel}<span class="dss-pc-stat-l">{statLabel}</span>{/if}
    </span>
  {:else}
    <span></span>
  {/if}
{/snippet}

{#if size === 'compact'}
  {#if onclick}
    <button class="dss-pc-row" {onclick} type="button">{@render compactBody()}</button>
  {:else}
    <div class="dss-pc-row">{@render compactBody()}</div>
  {/if}

{:else if size === 'standard'}
  <div class="dss-pc-card">
    <div class="dss-pc-head">
      {#if showPhoto}
        <span class="dss-pc-av dss-pc-av--lg">{@render photoImg()}<span class={`dss-tn dss-tn--badge dss-tn--badge-lg ${team} ${captain ? 'captain' : ''}`}>{jersey}</span></span>
      {:else}
        <span class={`dss-tn ${team} large ${captain ? 'captain' : ''}`}>{jersey}</span>
      {/if}
      <div class="dss-pc-who">
        <svelte:element this={heading.tag} class="dss-pc-nm">{name}</svelte:element>
        {@render roleLine()}
      </div>
    </div>
    {@render vitalsGrid()}
  </div>

{:else}
  <div class={showPhoto ? 'dss-pc-hero dss-pc-hero--photo' : 'dss-pc-hero'}>
    <div class="dss-pc-hero-left">
      {#if showPhoto}
        {@render photoImg()}
        <span class={`dss-tn dss-tn--badge dss-tn--badge-lg ${team} ${captain ? 'captain' : ''}`}>{jersey}</span>
      {:else}
        <span class={`dss-tn hero ${team} ${captain ? 'captain' : ''}`}>{jersey}</span>
      {/if}
    </div>
    <div class="dss-pc-hero-right">
      <svelte:element this={heading.tag} class="dss-pc-nm">{name}</svelte:element>
      {@render roleLine()}
      {@render vitalsGrid()}
    </div>
  </div>
{/if}

// react/PlayerCard.tsx
import { useState, type MouseEventHandler } from 'react';
import { cn } from './cn';
import { useHeadingTag, type HeadingTag } from './HeadingLevel';

export type PlayerCardSize = 'compact' | 'standard' | 'hero';
export type PlayerTeam = 'heim' | 'gast';

export interface PlayerVital {
  label: string;
  value: string | number;
  /** Hebt den Wert in Amber hervor. */
  accent?: boolean;
}

export interface PlayerCardProps {
  size?: PlayerCardSize;
  jersey: string | number;
  name: string;
  position?: string;
  team?: PlayerTeam;
  captain?: boolean;
  age?: string;
  heightCm?: string;
  /** Rolle/Funktion im Team (z. B. „Spielmacher“), nur in compact sichtbar. */
  playerRole?: string;
  vitals?: PlayerVital[];
  /** Hauptstatistik der compact-Zeile mit Beschriftung. */
  stat?: string | number | null;
  statLabel?: string;
  /** Nur compact: mit onClick wird die Zeile ein Button. */
  onClick?: MouseEventHandler<HTMLButtonElement>;
  /** Überschriftenebene des Namens in standard/hero, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
  titleAs?: HeadingTag;
  /** Foto-URL: ersetzt die Trikotmarke; die Trikotnummer bleibt als Badge (hero: Porträtfläche). Leer oder bei Ladefehler: Trikotmarke. */
  photo?: string;
  /** Alternativtext des Fotos; Standard leer (dekorativ, der Name steht daneben). */
  photoAlt?: string;
  className?: string;
}

function Vitals({ vitals }: { vitals: PlayerVital[] }) {
  if (vitals.length === 0) return null;
  return (
    <div className="dss-pc-vitals">
      {vitals.map((vital) => (
        <div key={vital.label}>
          <div className={cn('dss-pc-v', vital.accent && 'dss-pc-v--amber')}>{vital.value}</div>
          <div className="dss-pc-l">{vital.label}</div>
        </div>
      ))}
    </div>
  );
}

/** Spielerprimitive in drei Maßstäben: compact (Listenzeile), standard (Karte), hero (dunkle Großkarte). */
export function PlayerCard({
  size = 'standard',
  jersey,
  name,
  position = '',
  team = 'heim',
  captain = false,
  age = '',
  heightCm = '',
  playerRole = '',
  vitals = [],
  stat = null,
  statLabel = '',
  onClick,
  titleAs,
  photo = '',
  photoAlt = '',
  className,
}: PlayerCardProps) {
  const Heading = useHeadingTag(titleAs);
  // Eine URL, die nicht lädt, wird gemerkt: dann erscheint wieder die Trikotmarke (kein kaputtes Bildsymbol)
  const [failedUrl, setFailedUrl] = useState('');
  const showPhoto = Boolean(photo) && photo !== failedUrl;
  const imgSize = size === 'compact' ? 32 : size === 'standard' ? 64 : 200;
  const img = (
    <img
      className="dss-pc-img"
      src={photo}
      alt={photoAlt}
      width={imgSize}
      height={imgSize}
      loading="lazy"
      decoding="async"
      onError={() => setFailedUrl(photo)}
    />
  );

  const posClass = position ? `dss-pos ${position.toLowerCase()}` : '';
  const role = (
    <div className="dss-pc-role">
      {position ? <span className={posClass}>{position}</span> : null}
      {captain ? <span className="dss-pc-cap">Kapitän</span> : null}
      {age ? <span>{age}</span> : null}
      {heightCm ? <span>{heightCm} cm</span> : null}
    </div>
  );

  if (size === 'compact') {
    const body = (
      <>
        {showPhoto ? (
          <span className="dss-pc-av">
            {img}
            <span className={cn('dss-tn', 'dss-tn--badge', team, captain && 'captain')}>{jersey}</span>
          </span>
        ) : (
          <span className={cn('dss-tn', team, 'small', captain && 'captain')}>{jersey}</span>
        )}
        <span className="dss-pc-who">
          <span className="dss-pc-name">
            {name}
            {captain ? ' (C)' : ''}
          </span>
          {position || playerRole ? (
            <span className="dss-pc-meta">
              {position}
              {playerRole ? ` · ${playerRole}` : ''}
            </span>
          ) : null}
        </span>
        {/* Pill nur visuell: die Position steht schon in der Meta-Zeile. Leeres <span /> = Platzhalter für die Grid-Spalte. */}
        {position ? <span className={posClass} aria-hidden="true">{position}</span> : <span />}
        {stat !== null ? (
          <span className="dss-pc-stat">
            {stat}
            {statLabel ? <span className="dss-pc-stat-l">{statLabel}</span> : null}
          </span>
        ) : (
          // Platzhalter für die Grid-Spalte der Statistik
          <span />
        )}
      </>
    );
    return onClick ? (
      <button type="button" className={cn('dss-pc-row', className)} onClick={onClick}>
        {body}
      </button>
    ) : (
      <div className={cn('dss-pc-row', className)}>{body}</div>
    );
  }

  if (size === 'standard') {
    return (
      <div className={cn('dss-pc-card', className)}>
        <div className="dss-pc-head">
          {showPhoto ? (
            <span className="dss-pc-av dss-pc-av--lg">
              {img}
              <span className={cn('dss-tn', 'dss-tn--badge', 'dss-tn--badge-lg', team, captain && 'captain')}>{jersey}</span>
            </span>
          ) : (
            <span className={cn('dss-tn', team, 'large', captain && 'captain')}>{jersey}</span>
          )}
          <div className="dss-pc-who">
            <Heading className="dss-pc-nm">{name}</Heading>
            {role}
          </div>
        </div>
        <Vitals vitals={vitals} />
      </div>
    );
  }

  return (
    <div className={cn('dss-pc-hero', showPhoto && 'dss-pc-hero--photo', className)}>
      <div className="dss-pc-hero-left">
        {showPhoto ? (
          <>
            {img}
            <span className={cn('dss-tn', 'dss-tn--badge', 'dss-tn--badge-lg', team, captain && 'captain')}>{jersey}</span>
          </>
        ) : (
          <span className={cn('dss-tn', 'hero', team, captain && 'captain')}>{jersey}</span>
        )}
      </div>
      <div className="dss-pc-hero-right">
        <Heading className="dss-pc-nm">{name}</Heading>
        {role}
        <Vitals vitals={vitals} />
      </div>
    </div>
  );
}
