// svelte/Stepper.svelte
<script lang="ts">
  /**
   * DSS Stepper · Svelte 5
   * --------------------------------------------------------------
   * Schrittanzeige für Setup-Wizards, Spiel-Vorbereitung, Onboarding.
   * Drei Layouts mit demselben Datenmodell. Nutzt nur Klassen aus
   * css/components.css.
   *
   *   horizontal — Punkte + Verbindungslinien (Standard, Desktop)
   *   compact    — einzeilige Fortschrittsleiste mit aktuellem Schritt
   *   vertical   — gestapelte Liste mit Beschreibung (Sidebar-Wizards)
   *
   * Schrittzustand: done (grün, anklickbar) · current (Amber) · pending (gedämpft).
   * Der Punkt ist nur ein Button, wenn `onstep` gesetzt und der Schritt nicht
   * pending ist; sonst eine reine Anzeige.
   */
  type Step = {
    id: string;
    label: string;
    description?: string;
    state: 'done' | 'current' | 'pending';
  };

  let {
    steps,
    variant = 'horizontal',
    onstep,
    ariaLabel = 'Fortschritt',
  }: {
    steps: Step[];
    variant?: 'horizontal' | 'compact' | 'vertical';
    onstep?: (id: string) => void;
    ariaLabel?: string;
  } = $props();

  const stateText = { done: 'erledigt', current: 'aktuell', pending: 'ausstehend' } as const;

  let currentIdx = $derived(steps.findIndex((s) => s.state === 'current'));
  let doneCount = $derived(steps.filter((s) => s.state === 'done').length);
</script>

{#snippet dot(s: Step, i: number)}
  {#if onstep && s.state !== 'pending'}
    <button type="button" class="dss-step-dot" aria-label={s.label} onclick={() => onstep?.(s.id)}>
      {#if s.state === 'done'}
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12.5l4.5 4.5L19 7"/></svg>
      {:else}
        <span aria-hidden="true">{i + 1}</span>
      {/if}
    </button>
  {:else}
    <span class="dss-step-dot" aria-hidden="true">
      {#if s.state === 'done'}
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12.5l4.5 4.5L19 7"/></svg>
      {:else}
        <span>{i + 1}</span>
      {/if}
    </span>
  {/if}
{/snippet}

{#if variant === 'horizontal'}
  <ol class="dss-step dss-step--h" aria-label={ariaLabel}>
    {#each steps as s, i (s.id)}
      <li class={`dss-step-item is-${s.state}`} aria-current={s.state === 'current' ? 'step' : undefined}>
        {@render dot(s, i)}
        <div class="dss-step-label">{s.label}<span class="dss-sr-only"> ({stateText[s.state]})</span></div>
        {#if i < steps.length - 1}<span class="dss-step-line" aria-hidden="true"></span>{/if}
      </li>
    {/each}
  </ol>

{:else if variant === 'compact'}
  <div class="dss-step dss-step--c" role="group" aria-label={ariaLabel}>
    <div class="dss-step-track" aria-hidden="true">
      <div class="dss-step-fill" style={`width: ${steps.length ? (doneCount / steps.length) * 100 : 0}%;`}></div>
    </div>
    <div class="dss-step-info">
      <span class="dss-step-num">{currentIdx + 1} / {steps.length}</span>
      <span class="dss-step-cur">{steps[currentIdx]?.label ?? '—'}</span>
    </div>
  </div>

{:else}
  <ol class="dss-step dss-step--v" aria-label={ariaLabel}>
    {#each steps as s, i (s.id)}
      <li class={`dss-step-item is-${s.state}`} aria-current={s.state === 'current' ? 'step' : undefined}>
        <div class="dss-step-rail">
          {@render dot(s, i)}
          {#if i < steps.length - 1}<span class="dss-step-vline" aria-hidden="true"></span>{/if}
        </div>
        <div class="dss-step-body">
          <div class="dss-step-label">{s.label}<span class="dss-sr-only"> ({stateText[s.state]})</span></div>
          {#if s.description}<div class="dss-step-desc">{s.description}</div>{/if}
        </div>
      </li>
    {/each}
  </ol>
{/if}

// react/Stepper.tsx
import type { ReactNode } from 'react';
import { Icon } from './Icon';
import { cn } from './cn';

export type StepState = 'done' | 'current' | 'pending';
export type StepperVariant = 'horizontal' | 'compact' | 'vertical';

export interface StepItem {
  id: string;
  label: string;
  description?: string;
  state: StepState;
}

export interface StepperProps {
  steps: StepItem[];
  variant?: StepperVariant;
  /** Macht erledigte und aktuelle Schritte klickbar (Buttons); ohne Angabe sind es reine Anzeigen. */
  onStep?: (id: string) => void;
  ariaLabel?: string;
  className?: string;
}

const STATE_TEXT: Record<StepState, string> = { done: 'erledigt', current: 'aktuell', pending: 'ausstehend' };

/** Schrittanzeige für mehrstufige Abläufe (Setup, Runden, Onboarding). */
export function Stepper({ steps, variant = 'horizontal', onStep, ariaLabel = 'Fortschritt', className }: StepperProps) {
  const currentIdx = steps.findIndex((s) => s.state === 'current');
  const doneCount = steps.filter((s) => s.state === 'done').length;

  const dot = (step: StepItem, index: number): ReactNode => {
    const content = step.state === 'done' ? <Icon name="check" size={14} /> : <span aria-hidden="true">{index + 1}</span>;
    if (onStep && step.state !== 'pending') {
      return (
        <button type="button" className="dss-step-dot" aria-label={`${index + 1}. ${step.label}`} onClick={() => onStep(step.id)}>
          {content}
        </button>
      );
    }
    return (
      <span className="dss-step-dot" aria-hidden="true">
        {content}
      </span>
    );
  };

  const label = (step: StepItem): ReactNode => (
    <div className="dss-step-label">
      {step.label}
      <span className="dss-sr-only"> ({STATE_TEXT[step.state]})</span>
    </div>
  );

  if (variant === 'compact') {
    return (
      <div className={cn('dss-step', 'dss-step--c', className)} role="group" aria-label={ariaLabel}>
        <div className="dss-step-track" aria-hidden="true">
          <div className="dss-step-fill" style={{ width: `${steps.length ? (doneCount / steps.length) * 100 : 0}%` }} />
        </div>
        <div className="dss-step-info">
          <span className="dss-step-num">
            {currentIdx + 1} / {steps.length}
          </span>
          <span className="dss-step-cur">{steps[currentIdx]?.label ?? '—'}</span>
        </div>
      </div>
    );
  }

  if (variant === 'vertical') {
    return (
      <ol className={cn('dss-step', 'dss-step--v', className)} aria-label={ariaLabel}>
        {steps.map((step, i) => (
          <li
            key={step.id}
            className={cn('dss-step-item', `is-${step.state}`)}
            aria-current={step.state === 'current' ? 'step' : undefined}
          >
            <div className="dss-step-rail">
              {dot(step, i)}
              {i < steps.length - 1 ? <span className="dss-step-vline" aria-hidden="true" /> : null}
            </div>
            <div className="dss-step-body">
              {label(step)}
              {step.description ? <div className="dss-step-desc">{step.description}</div> : null}
            </div>
          </li>
        ))}
      </ol>
    );
  }

  return (
    <ol className={cn('dss-step', 'dss-step--h', className)} aria-label={ariaLabel}>
      {steps.map((step, i) => (
        <li
          key={step.id}
          className={cn('dss-step-item', `is-${step.state}`)}
          aria-current={step.state === 'current' ? 'step' : undefined}
        >
          {dot(step, i)}
          {label(step)}
          {i < steps.length - 1 ? <span className="dss-step-line" aria-hidden="true" /> : null}
        </li>
      ))}
    </ol>
  );
}
