// svelte/Table.svelte
<script lang="ts">
  /**
   * DSS Table · Svelte 5
   * --------------------------------------------------------------
   * Datentabelle nach der Tables-Spec. Nutzt nur die Klassen aus
   * css/components.css.
   *
   * Dichten : touch (60px) · default (48px) · compact (40px) · dense (32px)
   * Flächen : hell (Standard) · dunkel (Kampfgericht-Tisch)
   * Features: sticky Kopf (sobald der Scrollbereich eine Höhe hat), Sortier-Pfeil +
   *           aria-sort, optionales Striping, tfoot-Summenzeile, Hover.
   *           Der Scrollbereich ist eine Region mit Namen (caption, sonst title) und per
   *           Tastatur erreichbar.
   *
   * Zellen kommen vom Aufrufer über die `rows`/`body`-Snippets. Hilfsklassen:
   *   .num · .num.lead · .num.dim · .center
   *   .dss-tn / .dss-pos / .dss-pill-s / .dss-player (Dekoration)
   */
  import type { Snippet } from 'svelte';
  import type { HeadingTag } from '../js/heading.js';
  import { useHeadingTag } from './heading-context.js';

  type Density = 'touch' | 'default' | 'compact' | 'dense';

  let {
    title = '',
    titleAs = undefined,
    meta = '',
    live = false,
    density = 'default',
    dark = false,
    striped = false,
    columns,
    rows,
    head = undefined,
    body,
    foot = undefined,
    caption = '',
    class: klass = '',
  }: {
    title?: string;
      /** Überschriftenebene, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
    titleAs?: HeadingTag;
    meta?: string;
    live?: boolean;
    density?: Density;
    dark?: boolean;
    striped?: boolean;
    columns?: { key: string; label: string; align?: 'left' | 'right' | 'center'; width?: string; sortable?: boolean; sort?: 'asc' | 'desc' | null }[];
    rows?: Snippet;
    head?: Snippet;
    body?: Snippet;
    foot?: Snippet;
    /** Unsichtbare Tabellenbeschriftung für Screenreader; benennt auch den Scrollbereich. */
    caption?: string;
    class?: string;
  } = $props();

  const heading = useHeadingTag(() => titleAs);
</script>

<div class={`dss-frame ${dark ? 'dss-frame--dark' : ''} ${klass}`}>
  {#if title || meta || live}
    <div class="dss-frame-head">
      {#if title}<svelte:element this={heading.tag} class="dss-frame-title">{title}</svelte:element>{:else}<span></span>{/if}
      <div class="dss-frame-meta">
        {#if meta}<span>{meta}</span>{/if}
        {#if live}<span class="dss-crumb"><span class="dss-crumb-dot" aria-hidden="true"></span> Live</span>{/if}
      </div>
    </div>
  {/if}

  <!-- svelte-ignore a11y_no_noninteractive_tabindex -- Fokussierbar mit Absicht: Tastaturnutzer müssen den scrollbaren Bereich erreichen (WCAG 2.1.1) -->
  <div class="dss-table-scroll" role="region" tabindex="0" aria-label={caption || title || 'Tabelle'}>
    <table class={`dss-tbl dss-tbl--${density} ${striped ? 'dss-tbl--striped' : ''}`}>
      {#if caption}<caption class="dss-sr-only">{caption}</caption>{/if}
      {#if columns}
        <thead>
          <tr>
            {#each columns as col (col.key)}
              <th
                scope="col"
                class={`${col.align ?? 'left'} ${col.sortable ? 'sortable' : ''} ${col.sort ? `sort-${col.sort}` : ''}`}
                style={col.width ? `width: ${col.width};` : ''}
                aria-sort={col.sort === 'asc' ? 'ascending' : col.sort === 'desc' ? 'descending' : undefined}
              >{col.label}</th>
            {/each}
          </tr>
        </thead>
      {/if}
      {#if head && !columns}<thead>{@render head()}</thead>{/if}
      {#if body || rows}<tbody>{@render (body ?? rows)?.()}</tbody>{/if}
      {#if foot}<tfoot>{@render foot()}</tfoot>{/if}
    </table>
  </div>
</div>

// react/Table.tsx
import type { ReactNode } from 'react';
import { cn } from './cn';
import { useHeadingTag, type HeadingTag } from './HeadingLevel';

export type TableDensity = 'touch' | 'default' | 'compact' | 'dense';

export interface TableColumn {
  key: string;
  label: ReactNode;
  align?: 'left' | 'right' | 'center';
  width?: string;
  sortable?: boolean;
  /** Aktuelle Sortierrichtung; setzt `aria-sort` und den Pfeil. */
  sort?: 'asc' | 'desc' | null;
}

export interface TableProps {
  title?: ReactNode;
  /** Überschriftenebene des Titels, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
  titleAs?: HeadingTag;
  meta?: ReactNode;
  live?: boolean;
  density?: TableDensity;
  dark?: boolean;
  striped?: boolean;
  /** Einfacher Kopf aus Spaltendefinitionen; alternativ `head` für eigene Kopfzeilen. */
  columns?: TableColumn[];
  /** Eigene Kopfzeilen; wird ignoriert, wenn `columns` gesetzt ist. */
  head?: ReactNode;
  /** Zeilen des tbody (`<tr>`-Elemente). */
  children?: ReactNode;
  foot?: ReactNode;
  /** Unsichtbare Tabellenbeschriftung für Screenreader; benennt auch den Scrollbereich (sonst der Titel). */
  caption?: string;
  className?: string;
}

const ARIA_SORT = { asc: 'ascending', desc: 'descending' } as const;

/** Datentabelle im DSS-Rahmen (Titelzeile optional). Zellen liefert die Anwendung als `<tr>`-Kinder. */
export function Table({
  title,
  titleAs,
  meta,
  live = false,
  density = 'default',
  dark = false,
  striped = false,
  columns,
  head,
  children,
  foot,
  caption,
  className,
}: TableProps) {
  const Heading = useHeadingTag(titleAs);
  const hasHead = Boolean(title || meta || live);
  return (
    <div className={cn('dss-frame', dark && 'dss-frame--dark', className)}>
      {hasHead ? (
        <div className="dss-frame-head">
          {title ? <Heading className="dss-frame-title">{title}</Heading> : <span />}
          <div className="dss-frame-meta">
            {meta ? <span>{meta}</span> : null}
            {live ? (
              <span className="dss-crumb">
                <span className="dss-crumb-dot" aria-hidden="true" /> Live
              </span>
            ) : null}
          </div>
        </div>
      ) : null}
      <div className="dss-table-scroll" role="region" tabIndex={0} aria-label={caption || (typeof title === 'string' && title) || 'Tabelle'}>
        <table className={cn('dss-tbl', `dss-tbl--${density}`, striped && 'dss-tbl--striped')}>
          {caption ? <caption className="dss-sr-only">{caption}</caption> : null}
          {columns ? (
            <thead>
              <tr>
                {columns.map((col) => (
                  <th
                    key={col.key}
                    scope="col"
                    className={cn(col.align ?? 'left', col.sortable && 'sortable', col.sort && `sort-${col.sort}`)}
                    style={col.width ? { width: col.width } : undefined}
                    aria-sort={col.sort ? ARIA_SORT[col.sort] : undefined}
                  >
                    {col.label}
                  </th>
                ))}
              </tr>
            </thead>
          ) : null}
          {!columns && head ? <thead>{head}</thead> : null}
          <tbody>{children}</tbody>
          {foot ? <tfoot>{foot}</tfoot> : null}
        </table>
      </div>
    </div>
  );
}
