// react/AppNav.tsx
import { useEffect, useId, useRef, useState, type KeyboardEvent, type ReactNode } from 'react';
import { Icon } from './Icon';
import { cn } from './cn';

export interface AppNavLink {
  id: string;
  label: string;
  href: string;
  /** Gesperrt: nicht fokussierbar, mit Hinweis (Tooltip + Screenreader). */
  disabled?: boolean;
  hint?: string;
}

export interface AppNavGroup {
  id: string;
  label: string;
  items: AppNavLink[];
}

export type AppNavItem = AppNavLink | AppNavGroup;
export type AppNavTone = 'light' | 'dark';

export interface AppNavLinkRenderProps {
  item: AppNavLink;
  className: string;
  ariaCurrent: 'page' | undefined;
  /** Beim Navigieren aufrufen (schließt Dropdown und mobiles Menü). */
  onNavigate: () => void;
  children: ReactNode;
}

export interface AppNavProps {
  items: AppNavItem[];
  /** Aktueller Pfad; ein Link mit gleichem `href` ist aktiv (`aria-current="page"`). */
  currentHref?: string;
  tone?: AppNavTone;
  ariaLabel?: string;
  /** Beschriftung des Hamburger-Buttons (unter 720 px). */
  menuLabel?: string;
  /** Platz rechts in der Leiste, z. B. für einen späteren Turnierumschalter. */
  context?: ReactNode;
  /** Eigene Link-Darstellung, z. B. für React Router (`Link` statt `a`). */
  renderLink?: (props: AppNavLinkRenderProps) => ReactNode;
  /** Begrenzt den Inhalt auf --dss-shell-max (Hintergrund bleibt voll breit). */
  contained?: boolean;
  className?: string;
}

const isGroup = (item: AppNavItem): item is AppNavGroup => 'items' in item;
const slug = (id: string) => id.replace(/[^A-Za-z0-9_-]/g, '-');

/** Hauptnavigation mit Gruppen-Dropdowns (Disclosure), gesperrten Einträgen und mobilem Hamburger-Menü. */
export function AppNav({
  items,
  currentHref,
  tone = 'light',
  ariaLabel = 'Hauptnavigation',
  menuLabel = 'Menü',
  context,
  renderLink,
  contained = false,
  className,
}: AppNavProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [openGroup, setOpenGroup] = useState<string | null>(null);
  const rootRef = useRef<HTMLElement>(null);
  const toggleRef = useRef<HTMLButtonElement>(null);
  const triggers = useRef<Record<string, HTMLButtonElement | null>>({});
  const baseId = useId();

  useEffect(() => {
    if (!openGroup) return;
    const onMouseDown = (event: MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) setOpenGroup(null);
    };
    document.addEventListener('mousedown', onMouseDown);
    return () => document.removeEventListener('mousedown', onMouseDown);
  }, [openGroup]);

  const closeAll = () => {
    setOpenGroup(null);
    setMenuOpen(false);
  };

  const onKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    if (event.key !== 'Escape') return;
    if (openGroup) {
      const id = openGroup;
      setOpenGroup(null);
      triggers.current[id]?.focus();
    } else if (menuOpen) {
      setMenuOpen(false);
      toggleRef.current?.focus();
    }
  };

  const isCurrent = (item: AppNavLink) => currentHref !== undefined && item.href === currentHref;

  const renderItemLink = (item: AppNavLink): ReactNode => {
    if (item.disabled) {
      return (
        <span role="link" aria-disabled="true" className="dss-appnav-link is-disabled" title={item.hint}>
          {item.label}
          {item.hint ? <span className="dss-sr-only"> – {item.hint}</span> : null}
        </span>
      );
    }
    const current = isCurrent(item);
    const linkClass = cn('dss-appnav-link', current && 'is-active');
    const ariaCurrent = current ? 'page' : undefined;
    if (renderLink) {
      return renderLink({ item, className: linkClass, ariaCurrent, onNavigate: closeAll, children: item.label });
    }
    return (
      <a href={item.href} className={linkClass} aria-current={ariaCurrent} onClick={closeAll}>
        {item.label}
      </a>
    );
  };

  return (
    <nav
      ref={rootRef}
      aria-label={ariaLabel}
      className={cn('dss-appnav', `dss-appnav--${tone}`, contained && 'dss-appnav--contained', menuOpen && 'is-open', className)}
      onKeyDown={onKeyDown}
      onBlur={(event) => {
        // Nur schließen, wenn der Fokus auf ein Element außerhalb wandert (relatedTarget null = z. B. Safari-Klick, nicht schließen).
        const next = event.relatedTarget as Node | null;
        if (openGroup && next && !event.currentTarget.contains(next)) setOpenGroup(null);
      }}
    >
      <div className="dss-appnav-bar">
        <button
          ref={toggleRef}
          type="button"
          className="dss-appnav-toggle"
          aria-expanded={menuOpen}
          aria-controls={`${baseId}-list`}
          onClick={() => setMenuOpen((open) => !open)}
        >
          <Icon name={menuOpen ? 'x' : 'menu'} size={20} />
          <span>{menuLabel}</span>
        </button>
        <ul id={`${baseId}-list`} className="dss-appnav-list">
          {items.map((item) => {
            if (!isGroup(item)) {
              return (
                <li key={item.id} className="dss-appnav-item">
                  {renderItemLink(item)}
                </li>
              );
            }
            const open = openGroup === item.id;
            const panelId = `${baseId}-${slug(item.id)}`;
            return (
              <li key={item.id} className="dss-appnav-item">
                <button
                  ref={(el) => {
                    triggers.current[item.id] = el;
                  }}
                  type="button"
                  className={cn('dss-appnav-group-btn', item.items.some(isCurrent) && 'is-active', open && 'is-open')}
                  aria-expanded={open}
                  aria-controls={panelId}
                  onClick={() => setOpenGroup(open ? null : item.id)}
                >
                  {item.label}
                  <Icon name="chevron-d" size={16} className="dss-appnav-chev" />
                </button>
                <ul id={panelId} className="dss-appnav-panel" hidden={!open}>
                  {item.items.map((child) => (
                    <li key={child.id}>{renderItemLink(child)}</li>
                  ))}
                </ul>
              </li>
            );
          })}
        </ul>
        {context ? <div className="dss-appnav-context">{context}</div> : null}
      </div>
    </nav>
  );
}

// svelte/AppNav.svelte
<script lang="ts" module>
  let seq = 0;
</script>

<script lang="ts">
  /**
   * DSS AppNav · Svelte 5
   * --------------------------------------------------------------
   * Hauptnavigation mit Gruppen-Dropdowns (Disclosure), gesperrten
   * Einträgen und mobilem Hamburger-Menü (< 720 px). Nutzt nur Klassen
   * aus css/components.css. Aktiv ist der Link, dessen href `currentHref`
   * entspricht (aria-current="page").
   */
  import type { Snippet } from 'svelte';
  import Icon from './Icon.svelte';

  type Link = { id: string; label: string; href: string; disabled?: boolean; hint?: string };
  type Group = { id: string; label: string; items: Link[] };
  type Item = Link | Group;

  let {
    items,
    currentHref = '',
    tone = 'light',
    ariaLabel = 'Hauptnavigation',
    menuLabel = 'Menü',
    context,
    contained = false,
  }: {
    items: Item[];
    currentHref?: string;
    tone?: 'light' | 'dark';
    ariaLabel?: string;
    menuLabel?: string;
    /** Platz rechts in der Leiste, z. B. für einen späteren Turnierumschalter. */
    context?: Snippet;
    /** Begrenzt den Inhalt auf --dss-shell-max (Hintergrund bleibt voll breit). */
    contained?: boolean;
  } = $props();

  const baseId = `dss-appnav-${++seq}`;
  let menuOpen = $state(false);
  let openGroup = $state<string | null>(null);
  let root: HTMLElement | undefined = $state();
  let toggleEl: HTMLButtonElement | undefined = $state();
  const triggers: Record<string, HTMLButtonElement | undefined> = {};

  const slug = (id: string) => id.replace(/[^A-Za-z0-9_-]/g, '-');
  const isGroup = (item: Item): item is Group => 'items' in item;
  const isCurrent = (link: Link) => currentHref !== '' && link.href === currentHref;

  function closeAll() {
    openGroup = null;
    menuOpen = false;
  }

  function onKeydown(event: KeyboardEvent) {
    if (event.key !== 'Escape') return;
    if (openGroup) {
      const id = openGroup;
      openGroup = null;
      triggers[id]?.focus();
    } else if (menuOpen) {
      menuOpen = false;
      toggleEl?.focus();
    }
  }

  function onFocusout(event: FocusEvent) {
    // Nur schließen, wenn der Fokus auf ein Element außerhalb wandert (relatedTarget null = z. B. Safari-Klick, nicht schließen).
    const next = event.relatedTarget as Node | null;
    if (openGroup && next && root && !root.contains(next)) openGroup = null;
  }

  function onWindowMousedown(event: MouseEvent) {
    if (openGroup && root && !root.contains(event.target as Node)) openGroup = null;
  }
</script>

<svelte:window onmousedown={onWindowMousedown} />

{#snippet link(l: Link)}
  {#if l.disabled}
    <span role="link" aria-disabled="true" class="dss-appnav-link is-disabled" title={l.hint}>
      {l.label}{#if l.hint}<span class="dss-sr-only"> – {l.hint}</span>{/if}
    </span>
  {:else}
    <a
      class="dss-appnav-link"
      class:is-active={isCurrent(l)}
      href={l.href}
      aria-current={isCurrent(l) ? 'page' : undefined}
      onclick={closeAll}
    >{l.label}</a>
  {/if}
{/snippet}

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<nav
  bind:this={root}
  class="dss-appnav dss-appnav--{tone}"
  class:dss-appnav--contained={contained}
  class:is-open={menuOpen}
  aria-label={ariaLabel}
  onkeydown={onKeydown}
  onfocusout={onFocusout}
>
  <div class="dss-appnav-bar">
    <button
      bind:this={toggleEl}
      type="button"
      class="dss-appnav-toggle"
      aria-expanded={menuOpen}
      aria-controls="{baseId}-list"
      onclick={() => (menuOpen = !menuOpen)}
    >
      <Icon name={menuOpen ? 'x' : 'menu'} size={20} />
      <span>{menuLabel}</span>
    </button>
    <ul id="{baseId}-list" class="dss-appnav-list">
      {#each items as item (item.id)}
        {#if isGroup(item)}
          <li class="dss-appnav-item">
            <button
              bind:this={triggers[item.id]}
              type="button"
              class="dss-appnav-group-btn"
              class:is-active={item.items.some(isCurrent)}
              class:is-open={openGroup === item.id}
              aria-expanded={openGroup === item.id}
              aria-controls="{baseId}-{slug(item.id)}"
              onclick={() => (openGroup = openGroup === item.id ? null : item.id)}
            >
              {item.label}
              <Icon name="chevron-d" size={16} class="dss-appnav-chev" />
            </button>
            <ul id="{baseId}-{slug(item.id)}" class="dss-appnav-panel" hidden={openGroup !== item.id}>
              {#each item.items as child (child.id)}
                <li>{@render link(child)}</li>
              {/each}
            </ul>
          </li>
        {:else}
          <li class="dss-appnav-item">{@render link(item)}</li>
        {/if}
      {/each}
    </ul>
    {#if context}<div class="dss-appnav-context">{@render context()}</div>{/if}
  </div>
</nav>
