// react/Banner.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { SeverityIcon, type Severity } from './SeverityIcon';
import { cn } from './cn';

export type BannerSeverity = Severity;

export interface BannerProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  severity?: BannerSeverity;
  title?: ReactNode;
  icon?: boolean;
}

/** Inline-Hinweis. role: "alert" für warn/danger, "status" für info/ok (überschreibbar). */
export function Banner({ severity = 'info', title, icon = true, role, className, children, ...rest }: BannerProps) {
  const resolvedRole = role ?? (severity === 'warn' || severity === 'danger' ? 'alert' : 'status');
  return (
    <div role={resolvedRole} className={cn('dss-banner', `dss-banner--${severity}`, className)} {...rest}>
      {icon ? <SeverityIcon severity={severity} className="dss-banner-icon" /> : null}
      <div className="dss-banner-body">
        {title ? <p className="dss-banner-title">{title}</p> : null}
        {children}
      </div>
    </div>
  );
}

// svelte/Banner.svelte
<script lang="ts">
  /**
   * DSS Banner · Svelte 5
   * --------------------------------------------------------------
   * Inline-Hinweis (info · ok · warn · danger). Nutzt nur die Klassen aus
   * css/components.css. `role` ist standardmäßig "alert" für warn/danger
   * und "status" für info/ok.
   */
  import type { Snippet } from 'svelte';

  type Severity = 'info' | 'ok' | 'warn' | 'danger';

  let {
    severity = 'info',
    title = '',
    icon = true,
    role = undefined,
    children,
  }: {
    severity?: Severity;
    title?: string;
    icon?: boolean;
    role?: 'alert' | 'status' | 'none';
    children: Snippet;
  } = $props();

  const resolvedRole = $derived(role ?? (severity === 'warn' || severity === 'danger' ? 'alert' : 'status'));
</script>

<div class="dss-banner dss-banner--{severity}" role={resolvedRole}>
  {#if icon}
    <svg class="dss-banner-icon" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
      {#if severity === 'danger'}
        <g stroke-width="1.8"><circle cx="8" cy="8" r="6.5" /><path d="M5.2 10.8l5.6-5.6" /></g>
      {:else if severity === 'warn'}
        <g stroke-width="1.8"><path d="M8 1.5L15 14H1z" /><path d="M8 6v3M8 11.5v.05" /></g>
      {:else if severity === 'ok'}
        <g stroke-width="2.2"><path d="M3 8.2l3.5 3.5L13 5" /></g>
      {:else}
        <g stroke-width="1.8"><circle cx="8" cy="8" r="6.5" /><path d="M8 7v4M8 4.5v.05" /></g>
      {/if}
    </svg>
  {/if}
  <div class="dss-banner-body">
    {#if title}<p class="dss-banner-title">{title}</p>{/if}
    {@render children()}
  </div>
</div>
