// react/BottomNav.tsx
import { useState, type ReactNode } from 'react';
import { Icon, type IconName } from './Icon';
import { cn } from './cn';

export interface BottomNavItem {
  id: string;
  /** Pflicht, auch für den FAB (wird dort zum zugänglichen Namen). */
  label: string;
  icon?: IconName;
  badge?: number | string;
  /** Hervorgehobene Mittelaktion (Standard-Icon `plus`). */
  fab?: boolean;
  /** Mit `href` wird der Eintrag ein Link statt eines Buttons. */
  href?: string;
}

export interface BottomNavProps {
  items: BottomNavItem[];
  /** Kontrolliert (value) oder unkontrolliert (defaultValue). */
  value?: string;
  defaultValue?: string;
  onValueChange?: (id: string) => void;
  /** Der FAB ändert die Auswahl nicht, er löst nur diese Aktion aus (mit der FAB-ID). */
  onAction?: (id: string) => void;
  ariaLabel?: string;
  className?: string;
}

/** Mobile Navigation am unteren Bildschirmrand (4–5 Einträge, optional zentraler FAB). */
export function BottomNav({
  items,
  value: valueProp,
  defaultValue,
  onValueChange,
  onAction,
  ariaLabel = 'Hauptnavigation',
  className,
}: BottomNavProps) {
  const [inner, setInner] = useState(defaultValue ?? items.find((item) => !item.fab)?.id ?? '');
  const value = valueProp ?? inner;

  const pick = (item: BottomNavItem) => {
    setInner(item.id);
    onValueChange?.(item.id);
  };

  return (
    <nav aria-label={ariaLabel} className={cn('dss-bnav', className)}>
      {items.map((item) => {
        if (item.fab) {
          const icon = <Icon name={item.icon ?? 'plus'} size={22} />;
          return item.href ? (
            <a key={item.id} className="dss-bnav-fab" href={item.href} aria-label={item.label} onClick={() => onAction?.(item.id)}>
              {icon}
            </a>
          ) : (
            <button key={item.id} type="button" className="dss-bnav-fab" aria-label={item.label} onClick={() => onAction?.(item.id)}>
              {icon}
            </button>
          );
        }
        const active = value === item.id;
        const itemClass = cn('dss-bnav-item', active && 'is-active');
        const body: ReactNode = (
          <>
            {item.icon ? <Icon name={item.icon} size={22} className="dss-bnav-ic" /> : null}
            <span className="dss-bnav-lbl">{item.label}</span>
            {item.badge !== undefined ? <span className="dss-bnav-badge">{item.badge}</span> : null}
          </>
        );
        return item.href ? (
          <a key={item.id} className={itemClass} href={item.href} aria-current={active ? 'page' : undefined} onClick={() => pick(item)}>
            {body}
          </a>
        ) : (
          <button key={item.id} type="button" className={itemClass} aria-current={active ? 'page' : undefined} onClick={() => pick(item)}>
            {body}
          </button>
        );
      })}
    </nav>
  );
}

// svelte/BottomNav.svelte
<script lang="ts">
  /**
   * DSS BottomNav · Svelte 5
   * --------------------------------------------------------------
   * Mobile Navigation am unteren Rand (Schiri-App, Coach-App, Zuschauer-Modus),
   * 4–5 Einträge, optional zentraler FAB. Nutzt nur Klassen aus css/components.css.
   *
   * Eintrag: { id, label, icon (Sprite-ID ohne '#'), badge?, fab?, href? }
   * Mit href wird der Eintrag ein Link statt eines Buttons. Das Label ist Pflicht,
   * auch für den FAB (zugänglicher Name).
   */
  type Item = {
    id: string;
    label: string;
    icon?: string;
    badge?: number | string;
    fab?: boolean;
    href?: string;
  };

  let {
    items,
    value = $bindable(''),
    onchange,
    onaction,
    ariaLabel = 'Hauptnavigation',
  }: {
    items: Item[];
    value?: string;
    onchange?: (id: string) => void;
    /** Der FAB ändert die Auswahl nicht, er löst nur diese Aktion aus (mit der FAB-ID). */
    onaction?: (id: string) => void;
    ariaLabel?: string;
  } = $props();

  $effect(() => {
    if (!value && items.length) value = (items.find((item) => !item.fab) ?? items[0]).id;
  });

  function pick(it: Item) {
    value = it.id;
    onchange?.(it.id);
  }
</script>

{#snippet fabIcon(it: Item)}
  {#if it.icon}
    <svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true" focusable="false"><use href={`#${it.icon}`}></use></svg>
  {:else}
    <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true" focusable="false"><path d="M12 5v14M5 12h14"/></svg>
  {/if}
{/snippet}

{#snippet itemBody(it: Item)}
  {#if it.icon}
    <svg class="dss-bnav-ic" viewBox="0 0 24 24" width="22" height="22" aria-hidden="true" focusable="false"><use href={`#${it.icon}`}></use></svg>
  {/if}
  <span class="dss-bnav-lbl">{it.label}</span>
  {#if it.badge !== undefined}<span class="dss-bnav-badge">{it.badge}</span>{/if}
{/snippet}

<nav class="dss-bnav" aria-label={ariaLabel}>
  {#each items as it (it.id)}
    {#if it.fab}
      {#if it.href}
        <a class="dss-bnav-fab" href={it.href} aria-label={it.label} onclick={() => onaction?.(it.id)}>{@render fabIcon(it)}</a>
      {:else}
        <button type="button" class="dss-bnav-fab" aria-label={it.label} onclick={() => onaction?.(it.id)}>{@render fabIcon(it)}</button>
      {/if}
    {:else if it.href}
      <a
        class="dss-bnav-item"
        class:is-active={value === it.id}
        href={it.href}
        aria-current={value === it.id ? 'page' : undefined}
        onclick={() => pick(it)}
      >{@render itemBody(it)}</a>
    {:else}
      <button
        type="button"
        class="dss-bnav-item"
        class:is-active={value === it.id}
        aria-current={value === it.id ? 'page' : undefined}
        onclick={() => pick(it)}
      >{@render itemBody(it)}</button>
    {/if}
  {/each}
</nav>
