// react/Breadcrumbs.tsx
import { Fragment } from 'react';
import { Icon } from './Icon';
import { cn } from './cn';

export interface BreadcrumbItem {
  label: string;
  /** Ohne href wird der Eintrag als Text gerendert (Zwischenschritt ohne Seite). */
  href?: string;
  /** Kontext-Kürzel, nur in der Variante `tagged` sichtbar. */
  tag?: string;
}

export type BreadcrumbVariant = 'plain' | 'tagged' | 'chip';

export interface BreadcrumbsProps {
  items: BreadcrumbItem[];
  variant?: BreadcrumbVariant;
  ariaLabel?: string;
  className?: string;
}

/** Pfadanzeige: plain (Seitenkopf), tagged (mit Kontext-Kürzeln) oder chip (mobil). Das letzte Element ist die aktuelle Seite. */
export function Breadcrumbs({ items, variant = 'plain', ariaLabel = 'Breadcrumb', className }: BreadcrumbsProps) {
  const base = variant === 'chip' ? 'dss-crumbs-chip' : 'dss-crumbs-item';

  return (
    <nav aria-label={ariaLabel} className={cn('dss-crumbs', `dss-crumbs--${variant}`, className)}>
      {items.map((item, index) => {
        const isLast = index === items.length - 1;
        const content = (
          <>
            {variant === 'tagged' && item.tag ? <span className="dss-crumbs-tag">{item.tag}</span> : null}
            {item.label}
          </>
        );
        return (
          <Fragment key={`${item.label}-${index}`}>
            {isLast ? (
              <span className={cn(base, 'is-current')} aria-current="page">
                {content}
              </span>
            ) : item.href ? (
              <a className={base} href={item.href}>
                {content}
              </a>
            ) : (
              <span className={base}>{content}</span>
            )}
            {isLast ? null : <Icon name="chevron-r" size={14} className="dss-crumbs-sep" />}
          </Fragment>
        );
      })}
    </nav>
  );
}

// svelte/Breadcrumbs.svelte
<script lang="ts">
  /**
   * DSS Breadcrumbs · Svelte 5
   * --------------------------------------------------------------
   * Drei Varianten, nutzt nur Klassen aus css/components.css:
   *   plain  — Pfad mit Chevron-Trennern (Seitenkopf)
   *   tagged — Pfad + Kontext-Kürzel je Eintrag (Admin / Archiv)
   *   chip   — Pill-Stil (mobil)
   *
   * Items: [{ label, href?, tag? }]. Das letzte Element ist die aktuelle Seite
   * (kein Link, aria-current="page"); Einträge ohne href sind reiner Text.
   */
  type Item = {
    label: string;
    href?: string;
    tag?: string;
  };

  let {
    items,
    variant = 'plain',
    ariaLabel = 'Breadcrumb',
  }: {
    items: Item[];
    variant?: 'plain' | 'tagged' | 'chip';
    ariaLabel?: string;
  } = $props();

  const base = $derived(variant === 'chip' ? 'dss-crumbs-chip' : 'dss-crumbs-item');
</script>

<nav class={`dss-crumbs dss-crumbs--${variant}`} aria-label={ariaLabel}>
  {#each items as it, i}
    {@const isLast = i === items.length - 1}
    {#if isLast}
      <span class={`${base} is-current`} aria-current="page">
        {#if variant === 'tagged' && it.tag}<span class="dss-crumbs-tag">{it.tag}</span>{/if}
        {it.label}
      </span>
    {:else}
      {#if it.href}
        <a class={base} href={it.href}>
          {#if variant === 'tagged' && it.tag}<span class="dss-crumbs-tag">{it.tag}</span>{/if}
          {it.label}
        </a>
      {:else}
        <span class={base}>
          {#if variant === 'tagged' && it.tag}<span class="dss-crumbs-tag">{it.tag}</span>{/if}
          {it.label}
        </span>
      {/if}
      <svg class="dss-crumbs-sep" viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m9 6 6 6-6 6"/></svg>
    {/if}
  {/each}
</nav>
