// react/Checkbox.tsx
import { forwardRef, useId, type InputHTMLAttributes, type ReactNode } from 'react';
import { cn } from './cn';

export type CheckboxDensity = 'default' | 'compact';

export interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  label: ReactNode;
  /** Erklärender Zusatztext unter dem Label (wird per aria-describedby verknüpft). */
  hint?: ReactNode;
  density?: CheckboxDensity;
}

/** Natives Kontrollkästchen im DSS-Look; die Klickfläche ist das gesamte Label (≥ 44 px, kompakt 36 px). */
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(
  { label, hint, density = 'default', className, id, disabled, 'aria-describedby': describedByProp, ...rest },
  ref,
) {
  const autoId = useId();
  const inputId = id ?? autoId;
  const hintId = hint ? `${inputId}-hint` : undefined;
  const describedBy = [describedByProp, hintId].filter(Boolean).join(' ') || undefined;

  return (
    <label
      htmlFor={inputId}
      className={cn('dss-check', density === 'compact' && 'dss-check--compact', disabled && 'is-disabled')}
    >
      <input
        ref={ref}
        id={inputId}
        type="checkbox"
        className={cn('dss-check-input', className)}
        disabled={disabled}
        aria-describedby={describedBy}
        {...rest}
      />
      <span className="dss-check-text">
        <span className="dss-check-label">{label}</span>
        {hint ? (
          <span id={hintId} className="dss-check-hint">
            {hint}
          </span>
        ) : null}
      </span>
    </label>
  );
});

// svelte/Checkbox.svelte
<script lang="ts" module>
  let seq = 0;
</script>

<script lang="ts">
  /**
   * DSS Checkbox · Svelte 5
   * --------------------------------------------------------------
   * Natives Kontrollkästchen im DSS-Look. Die Klickfläche ist das
   * gesamte Label (≥ 44 px, `density="compact"` 36 px). Nutzt nur
   * die Klassen aus css/components.css.
   */
  let {
    label,
    hint = '',
    checked = $bindable(false),
    disabled = false,
    density = 'default',
    id = undefined,
    name = undefined,
    onchange = undefined,
  }: {
    label: string;
    hint?: string;
    checked?: boolean;
    disabled?: boolean;
    density?: 'default' | 'compact';
    id?: string;
    name?: string;
    onchange?: (checked: boolean) => void;
  } = $props();

  const autoId = `dss-check-${++seq}`;
  const inputId = $derived(id ?? autoId);
</script>

<label
  for={inputId}
  class="dss-check"
  class:dss-check--compact={density === 'compact'}
  class:is-disabled={disabled}
>
  <input
    id={inputId}
    {name}
    type="checkbox"
    class="dss-check-input"
    bind:checked
    {disabled}
    aria-describedby={hint ? `${inputId}-hint` : undefined}
    onchange={() => onchange?.(checked)}
  />
  <span class="dss-check-text">
    <span class="dss-check-label">{label}</span>
    {#if hint}<span id={`${inputId}-hint`} class="dss-check-hint">{hint}</span>{/if}
  </span>
</label>
