// react/EmptyState.tsx
import type { ReactNode } from 'react';
import { Icon, type IconName } from './Icon';
import { cn } from './cn';
import { useHeadingTag, type HeadingTag } from './HeadingLevel';

export type EmptyStateTone = 'neutral' | 'action' | 'error';

export interface EmptyStateProps {
  tone?: EmptyStateTone;
  title: string;
  body?: ReactNode;
  /** Sprite-Icon; ohne Angabe ein tonalitätsabhängiges Standard-Symbol. */
  icon?: IconName;
  /** Einfacher CTA-Button; für mehrere/andere Aktionen `actions` nutzen. */
  cta?: string;
  onCta?: () => void;
  actions?: ReactNode;
  /** Überschriftenebene des Titels, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
  titleAs?: HeadingTag;
  className?: string;
  /** Zusatz-Inhalt unter den Aktionen. */
  children?: ReactNode;
}

const CTA_VARIANT = { neutral: 'primary', action: 'amber', error: 'danger' } as const;

function ToneIcon({ tone }: { tone: EmptyStateTone }) {
  const common = {
    viewBox: '0 0 24 24',
    width: 28,
    height: 28,
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 1.6,
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
    'aria-hidden': true,
    focusable: false,
  };
  if (tone === 'error') {
    return (
      <svg {...common}>
        <path d="m12 4 10 17H2L12 4Z" />
        <path d="M12 10v5" />
        <circle cx="12" cy="18.2" r=".7" fill="currentColor" />
      </svg>
    );
  }
  if (tone === 'action') {
    return (
      <svg {...common}>
        <circle cx="12" cy="12" r="9" />
        <path d="M12 8v5" />
        <circle cx="12" cy="16.5" r=".7" fill="currentColor" />
      </svg>
    );
  }
  return (
    <svg {...common}>
      <rect x="4" y="5" width="16" height="14" rx="2" />
      <path d="M4 10h16" />
    </svg>
  );
}

/** Leer-, Hinweis- oder Fehlerzustand mit klarem nächsten Schritt. */
export function EmptyState({
  tone = 'neutral',
  title,
  body,
  icon,
  cta,
  onCta,
  actions,
  titleAs,
  className,
  children,
}: EmptyStateProps) {
  const Heading = useHeadingTag(titleAs);
  return (
    <div className={cn('dss-empty', `dss-empty--${tone}`, className)}>
      <div className="dss-empty-icon">{icon ? <Icon name={icon} size={28} /> : <ToneIcon tone={tone} />}</div>
      <Heading className="dss-empty-title">{title}</Heading>
      {body ? <p className="dss-empty-body">{body}</p> : null}
      {cta || actions ? (
        <div className="dss-empty-actions">
          {cta ? (
            <button type="button" className={cn('dss-btn', 'dss-btn--md', `dss-btn--${CTA_VARIANT[tone]}`)} onClick={onCta}>
              {cta}
            </button>
          ) : null}
          {actions}
        </div>
      ) : null}
      {children ? <div className="dss-empty-extra">{children}</div> : null}
    </div>
  );
}

// svelte/EmptyState.svelte
<script lang="ts">
  /**
   * DSS EmptyState · Svelte 5
   * --------------------------------------------------------------
   * Drei Tonalitäten für „hier ist nichts“-Zustände:
   *
   *   neutral — keine Daten / Erstnutzung (ruhig)
   *   action  — etwas fehlt, die Nutzerin kann es beheben (Amber)
   *   error   — Laden fehlgeschlagen, Wiederholen möglich (Rot)
   *
   * Immer einen nächsten Schritt anbieten (CTA, `actions` oder Hinweis).
   * Nutzt nur Klassen aus css/components.css.
   */
  import type { Snippet } from 'svelte';
  import type { HeadingTag } from '../js/heading.js';
  import { useHeadingTag } from './heading-context.js';

  let {
    tone = 'neutral',
    title,
    body = '',
    icon = '',
    cta = '',
    onclick,
    titleAs = undefined,
    actions,
    children,
  }: {
    tone?: 'neutral' | 'action' | 'error';
    title: string;
    body?: string;
    icon?: string; // Sprite-ID ohne #
    cta?: string;
    onclick?: () => void;
    /** Überschriftenebene, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
    titleAs?: HeadingTag;
    actions?: Snippet;
    children?: Snippet;
  } = $props();

  const heading = useHeadingTag(() => titleAs);

  const ctaVariant = $derived(tone === 'error' ? 'danger' : tone === 'action' ? 'amber' : 'primary');
</script>

<div class={`dss-empty dss-empty--${tone}`}>
  <div class="dss-empty-icon">
    {#if icon}
      <svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
        <use href={`#${icon}`}></use>
      </svg>
    {:else if tone === 'error'}
      <svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m12 4 10 17H2L12 4Z"/><path d="M12 10v5"/><circle cx="12" cy="18.2" r=".7" fill="currentColor"/></svg>
    {:else if tone === 'action'}
      <svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="9"/><path d="M12 8v5"/><circle cx="12" cy="16.5" r=".7" fill="currentColor"/></svg>
    {:else}
      <svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><rect x="4" y="5" width="16" height="14" rx="2"/><path d="M4 10h16"/></svg>
    {/if}
  </div>
  <svelte:element this={heading.tag} class="dss-empty-title">{title}</svelte:element>
  {#if body}<p class="dss-empty-body">{body}</p>{/if}
  {#if cta || actions}
    <div class="dss-empty-actions">
      {#if cta}
        <button type="button" class={`dss-btn dss-btn--md dss-btn--${ctaVariant}`} {onclick}>{cta}</button>
      {/if}
      {#if actions}{@render actions()}{/if}
    </div>
  {/if}
  {#if children}<div class="dss-empty-extra">{@render children()}</div>{/if}
</div>
