// react/PlayByPlay.tsx
import { cn } from './cn';
import { resolvePeriod } from '../js/periods.js';
import { useHeadingTag, type HeadingTag } from './HeadingLevel';

export type PbpTeam = 'heim' | 'gast' | 'none';
export type PbpKind = 'default' | 'score-2p' | 'score-3p' | 'ft' | 'foul' | 'timeout' | 'sub' | 'turnover';

export interface PbpEvent {
  id: string | number;
  /** „M:SS“ */
  time: string;
  /** Spielabschnitt ab 1 (mit `periods`): Chip „V1“ bis „V4“ bzw. „A1“ bis „A8“, „VL“ für die Verlängerung; Screenreader lesen „3. Viertel“. */
  period?: number;
  /** @deprecated Stattdessen `period`; ohne `period` wird der Text unverändert angezeigt („Q1“ … „OT“). */
  quarter?: string;
  team?: PbpTeam;
  kind?: PbpKind;
  title: string;
  /** Optionaler fett gesetzter Einleitungsteil. */
  titleBold?: string;
  detail?: string;
  /** Kumulierter Spielstand nach dem Ereignis. */
  score?: { heim: number; gast: number };
}

export interface PlayByPlayProps {
  events: PbpEvent[];
  title?: string;
  /** Überschriftenebene des Titels, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
  titleAs?: HeadingTag;
  meta?: string;
  live?: boolean;
  dark?: boolean;
  /** 4 Viertel (Standard) oder 8 Achtel (Mini-Basketball). */
  periods?: 4 | 8;
  className?: string;
}

const TEAM_TEXT = { heim: 'Heim:', gast: 'Gast:' } as const;

/** Live-Scoring-Ereignisstrom: Zeit, Teamstreifen, Aktion, Spielstand; neue Einträge blenden ein. */
export function PlayByPlay({
  events,
  title = 'Play-by-Play · neueste oben',
  titleAs,
  meta = '',
  live = true,
  dark = false,
  periods = 4,
  className,
}: PlayByPlayProps) {
  const Heading = useHeadingTag(titleAs);
  return (
    <div className={cn('dss-pbp-frame', dark && 'dss-pbp-frame--dark', className)}>
      <div className="dss-pbp-head">
        <Heading className="dss-pbp-title">{title}</Heading>
        <div className="dss-pbp-meta">
          {meta ? <span>{meta}</span> : null}
          {live ? (
            <span className="dss-pbp-live">
              <span className="dss-pbp-dot" aria-hidden="true" /> Live
            </span>
          ) : null}
        </div>
      </div>

      <div className="dss-pbp-feed" role="log" aria-label={title} tabIndex={0}>
        {events.map((event) => {
          const team = event.team ?? 'none';
          const abschnitt = resolvePeriod({ period: event.period, periods, quarter: event.quarter });
          return (
            <div key={event.id} className={cn('dss-pbp-event', `dss-pbp-event--${event.kind ?? 'default'}`)}>
              <div className="dss-pbp-time">
                {event.time}
                {abschnitt.short ? (
                  <span className="dss-pbp-q">
                    {abschnitt.alias ? (
                      abschnitt.label
                    ) : (
                      <>
                        <span aria-hidden="true">{abschnitt.short}</span>
                        <span className="dss-sr-only">{abschnitt.label}</span>
                      </>
                    )}
                  </span>
                ) : null}
              </div>
              <div className={cn('dss-pbp-strip', `dss-pbp-strip--${team}`)} aria-hidden="true" />
              <div className="dss-pbp-body">
                <div className="dss-pbp-action">
                  {team !== 'none' ? <span className="dss-sr-only">{TEAM_TEXT[team]} </span> : null}
                  {event.titleBold ? (
                    <>
                      <b>{event.titleBold}</b> ·{' '}
                    </>
                  ) : null}
                  {event.title}
                </div>
                {event.detail ? <div className="dss-pbp-detail">{event.detail}</div> : null}
              </div>
              {event.score ? (
                <div className="dss-pbp-score">
                  <span aria-hidden="true">
                    {event.score.heim}
                    <span className="dss-pbp-sep">:</span>
                    {event.score.gast}
                  </span>
                  <span className="dss-sr-only">{`Spielstand ${event.score.heim} zu ${event.score.gast}`}</span>
                </div>
              ) : null}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// svelte/PlayByPlay.svelte
<script lang="ts" module>
  export type PbpEvent = {
    id: string | number;
    time: string; // "M:SS"
    /** Spielabschnitt ab 1 (mit `periods`): Chip „V1“ bis „V4“ bzw. „A1“ bis „A8“, „VL“ für die Verlängerung. */
    period?: number;
    /** @deprecated Stattdessen `period`; ohne `period` wird der Text unverändert angezeigt. */
    quarter?: string; // freier Text, z. B. "Q1" .. "OT"
    team?: 'heim' | 'gast' | 'none';
    kind?: 'default' | 'score-2p' | 'score-3p' | 'ft' | 'foul' | 'timeout' | 'sub' | 'turnover';
    title: string;
    titleBold?: string;
    detail?: string;
    score?: { heim: number; gast: number };
  };
</script>

<script lang="ts">
  import { resolvePeriod } from '../js/periods.js';
  import type { HeadingTag } from '../js/heading.js';
  import { useHeadingTag } from './heading-context.js';
  /**
   * DSS PlayByPlay · Svelte 5
   * --------------------------------------------------------------
   * Live-Scoring-Ereignisstrom, chronologisch. Je Ereignis: Zeit (M:SS + Spielabschnitt),
   * 4 px Teamstreifen, Aktion (+ Detail), kumulierter Spielstand. Nutzt nur Klassen
   * aus css/components.css. Der Feed ist ein `role="log"` und per Tastatur scrollbar.
   *
   * Spielabschnitt: `period` je Ereignis und `periods` (4 Viertel, Standard, oder 8 Achtel) an der Komponente; der Chip
   * zeigt die Kurzform (V3, A5, VL), Screenreader lesen den vollen Text („3. Viertel“). `quarter` ist veraltet (Alias).
   *
   * Ereignisarten: default · score-2p · score-3p · ft · foul · timeout · sub · turnover
   */
  let {
    title = 'Play-by-Play · neueste oben',
    titleAs = undefined,
    meta = '',
    live = true,
    dark = false,
    periods = 4,
    events,
  }: {
    title?: string;
    /** Überschriftenebene, h2 bis h6. Rangfolge: `titleAs` vor der Ebene aus `HeadingLevel` vor h3. */
    titleAs?: HeadingTag;
    meta?: string;
    live?: boolean;
    dark?: boolean;
    periods?: 4 | 8;
    events: PbpEvent[];
  } = $props();

  const heading = useHeadingTag(() => titleAs);

  const teamText = { heim: 'Heim:', gast: 'Gast:' } as const;
</script>

<div class={`dss-pbp-frame ${dark ? 'dss-pbp-frame--dark' : ''}`}>
  <div class="dss-pbp-head">
    <svelte:element this={heading.tag} class="dss-pbp-title">{title}</svelte:element>
    <div class="dss-pbp-meta">
      {#if meta}<span>{meta}</span>{/if}
      {#if live}<span class="dss-pbp-live"><span class="dss-pbp-dot" aria-hidden="true"></span> Live</span>{/if}
    </div>
  </div>

  <div class="dss-pbp-feed" role="log" aria-label={title} tabindex="0">
    {#each events as e (e.id)}
      {@const abschnitt = resolvePeriod({ period: e.period, periods, quarter: e.quarter })}
      <div class={`dss-pbp-event dss-pbp-event--${e.kind ?? 'default'}`}>
        <div class="dss-pbp-time">
          {e.time}
          {#if abschnitt.short}
            <span class="dss-pbp-q">{#if abschnitt.alias}{abschnitt.label}{:else}<span aria-hidden="true">{abschnitt.short}</span><span class="dss-sr-only">{abschnitt.label}</span>{/if}</span>
          {/if}
        </div>
        <div class={`dss-pbp-strip dss-pbp-strip--${e.team ?? 'none'}`} aria-hidden="true"></div>
        <div class="dss-pbp-body">
          <div class="dss-pbp-action">
            {#if e.team && e.team !== 'none'}<span class="dss-sr-only">{teamText[e.team]} </span>{/if}
            {#if e.titleBold}<b>{e.titleBold}</b> · {/if}{e.title}
          </div>
          {#if e.detail}
            <div class="dss-pbp-detail">{e.detail}</div>
          {/if}
        </div>
        {#if e.score}
          <div class="dss-pbp-score"><span aria-hidden="true">{e.score.heim}<span class="dss-pbp-sep">:</span>{e.score.gast}</span><span class="dss-sr-only">{`Spielstand ${e.score.heim} zu ${e.score.gast}`}</span></div>
        {/if}
      </div>
    {/each}
  </div>
</div>
