// react/ScheduleGrid.tsx
import type { ReactNode } from 'react';
import { cn } from './cn';
import { ariaForResult, buildGrid, hasScore, stateLabel, winnerSide } from '../js/schedule.js';
import { LiveTag, ResultText, TeamName, type ScheduleRenderLink } from './ScheduleParts';
import type { ScheduleBreak, ScheduleDensity, ScheduleGame, ScheduleGridColumn } from './schedule-types';

export interface ScheduleGridProps {
  /** Jedes Spiel braucht `time` und `column` (passt zu einer `columns[].id`). */
  games: ScheduleGame[];
  /** Spalten (Hallen oder Felder) in Anzeige-Reihenfolge; `label` ist freier Text. */
  columns: ScheduleGridColumn[];
  /** Anwurfzeiten als Zeilen; ohne Angabe aus `games` abgeleitet. */
  slots?: string[];
  /** Pausen und Sperrzeiten als Zeile über alle Spalten. */
  breaks?: ScheduleBreak[];
  emptyLabel?: string;
  density?: ScheduleDensity;
  title?: ReactNode;
  titleAs?: 'h2' | 'h3' | 'h4';
  meta?: ReactNode;
  caption?: string;
  className?: string;
  renderLink?: ScheduleRenderLink;
  /** Zusätzlicher Inhalt in der Spielzelle, z. B. Konflikt-Badge. */
  renderNotice?: (game: ScheduleGame) => ReactNode;
}

/** Zeitraster: Anwurfzeiten als Zeilen, Hallen oder Felder als Spalten (empfohlen: höchstens drei). */
export function ScheduleGrid({
  games,
  columns,
  slots,
  breaks,
  emptyLabel = 'frei',
  density = 'default',
  title,
  titleAs: Heading = 'h3',
  meta,
  caption,
  className,
  renderLink,
  renderNotice,
}: ScheduleGridProps) {
  const rows = buildGrid({ games, columns, slots, breaks });
  const hasHead = Boolean(title || meta);

  const gameBlock = (game: ScheduleGame): ReactNode => {
    const winner = winnerSide(game);
    const own = game.heim?.own || game.gast?.own;
    const metaText = [game.nr, game.section].filter(Boolean).join(' · ');
    return (
      <div
        key={game.id}
        className={cn(
          'dss-sg-game',
          own && 'is-own',
          game.state === 'live' && 'is-live',
          game.state === 'cancelled' && 'is-cancelled',
          game.state === 'postponed' && 'is-postponed',
        )}
      >
        <div className="dss-sg-teams">
          {stateLabel(game.state) ? <span className="dss-sr-only">{`${stateLabel(game.state)} `}</span> : null}
          <TeamName team={game.heim} loser={winner === 'gast'} renderLink={renderLink} />
          <span className="dss-sch-sep" aria-hidden="true">
            {' – '}
          </span>
          <span className="dss-sr-only"> gegen </span>
          <TeamName team={game.gast} loser={winner === 'heim'} renderLink={renderLink} />
        </div>
        {game.state === 'live' ? <LiveTag /> : null}
        {(game.state === 'finished' || game.state === 'live') && hasScore(game, 'versus') ? (
          <div className="dss-sg-result">
            <ResultText
              visible={`${game.heim?.score} : ${game.gast?.score}`}
              spoken={ariaForResult(game, 'versus')}
              provisional={game.provisional}
            />
          </div>
        ) : null}
        {metaText ? <div className="dss-sg-meta">{metaText}</div> : null}
        {game.note ? <div className="dss-sch-note">{game.note}</div> : null}
        {renderNotice ? renderNotice(game) : null}
      </div>
    );
  };

  return (
    <div className={cn('dss-frame', className)}>
      {hasHead ? (
        <div className="dss-frame-head">
          {title ? <Heading className="dss-frame-title">{title}</Heading> : <span />}
          <div className="dss-frame-meta">{meta ? <span>{meta}</span> : null}</div>
        </div>
      ) : null}
      <div className="dss-table-scroll">
        <table role="table" className={cn('dss-tbl dss-sgrid', `dss-tbl--${density}`)}>
          {caption ? <caption className="dss-sr-only">{caption}</caption> : null}
          <thead role="rowgroup">
            <tr role="row">
              <th scope="col" role="columnheader" className="dss-sg-time">
                Zeit
              </th>
              {columns.map((column) => (
                <th key={column.id} scope="col" role="columnheader">
                  {column.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody role="rowgroup">
            {rows.map((row, index) => {
              if (row.kind === 'break') {
                return (
                  <tr key={`b-${index}`} role="row" className="dss-sg-break">
                    <th scope="row" role="rowheader" className="dss-sg-time">
                      {row.time}
                    </th>
                    <td role="cell" colSpan={columns.length}>
                      {row.label}
                    </td>
                  </tr>
                );
              }
              if (row.kind === 'bye') {
                return (
                  <tr key={`y-${index}`} role="row" className="dss-sg-bye">
                    <th scope="row" role="rowheader" className="dss-sg-time">
                      {row.time ?? ''}
                    </th>
                    <td role="cell" colSpan={columns.length}>
                      {row.game.heim ? `${row.game.heim.name} hat Freilos` : (row.game.note ?? 'Spielfrei')}
                    </td>
                  </tr>
                );
              }
              return (
                <tr key={`s-${row.time}-${index}`} role="row">
                  <th scope="row" role="rowheader" className="dss-sg-time">
                    {row.time}
                  </th>
                  {row.cells.map((cell, columnIndex) => (
                    <td
                      key={columns[columnIndex].id}
                      role="cell"
                      className={cn('dss-sg-cell', cell.length === 0 && 'is-empty')}
                      data-label={columns[columnIndex].label}
                    >
                      {cell.length === 0 ? <span className="dss-sg-empty">{emptyLabel}</span> : cell.map(gameBlock)}
                    </td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// svelte/ScheduleGrid.svelte
<script lang="ts">
  /**
   * DSS ScheduleGrid · Svelte 5
   * --------------------------------------------------------------
   * Zeitraster: Anwurfzeiten als Zeilen, Hallen oder Felder als Spalten
   * (empfohlen: höchstens drei). Nutzt ausschließlich die Klassen aus
   * css/components.css (kein eigener Scoped-Style); gleiche Struktur wie
   * die React-Fassung. Slot `notice`: zusätzlicher Inhalt in der Spielzelle.
   */
  import type { Snippet } from 'svelte';
  import { ariaForResult, buildGrid, hasScore, stateLabel, winnerSide } from '../js/schedule.js';
  import type { ScheduleBreak, ScheduleDensity, ScheduleGame, ScheduleGridColumn, ScheduleTeam } from '../js/schedule.js';

  let {
    games,
    columns,
    slots = undefined,
    breaks = undefined,
    emptyLabel = 'frei',
    density = 'default',
    title = '',
    meta = '',
    caption = '',
    class: klass = '',
    notice = undefined,
  }: {
    games: ScheduleGame[];
    columns: ScheduleGridColumn[];
    slots?: string[];
    breaks?: ScheduleBreak[];
    emptyLabel?: string;
    density?: ScheduleDensity;
    title?: string;
    meta?: string;
    caption?: string;
    class?: string;
    notice?: Snippet<[ScheduleGame]>;
  } = $props();

  const rows = $derived(buildGrid({ games, columns, slots, breaks }));
</script>

{#snippet team(t: ScheduleTeam | undefined, loser: boolean)}
  {@const current = t ?? { name: '?' }}
  <span class="dss-sch-team" class:is-loser={loser}>
    {#if current.href && !current.placeholder}
      <a class="dss-link" href={current.href}>{current.name}</a>
    {:else if current.placeholder}
      <span class="dss-sch-ph">{current.name}</span>
    {:else}
      {current.name}
    {/if}
  </span>
{/snippet}

{#snippet gameBlock(game: ScheduleGame)}
  {@const winner = winnerSide(game)}
  {@const own = game.heim?.own || game.gast?.own}
  {@const metaText = [game.nr, game.section].filter(Boolean).join(' · ')}
  <div
    class="dss-sg-game"
    class:is-own={own}
    class:is-live={game.state === 'live'}
    class:is-cancelled={game.state === 'cancelled'}
    class:is-postponed={game.state === 'postponed'}
  >
    <div class="dss-sg-teams">
      {#if stateLabel(game.state)}<span class="dss-sr-only">{`${stateLabel(game.state)} `}</span>{/if}
      {@render team(game.heim, winner === 'gast')}
      <span class="dss-sch-sep" aria-hidden="true"> – </span>
      <span class="dss-sr-only"> gegen </span>
      {@render team(game.gast, winner === 'heim')}
    </div>
    {#if game.state === 'live'}
      <span class="dss-match-live dss-sch-live"><span class="dss-match-pulse" aria-hidden="true"></span> Live</span>
    {/if}
    {#if (game.state === 'finished' || game.state === 'live') && hasScore(game, 'versus')}
      <div class="dss-sg-result">
        <span class="dss-sch-score" aria-hidden="true">{game.heim?.score} : {game.gast?.score}</span>
        <span class="dss-sr-only">{ariaForResult(game, 'versus')}</span>
        {#if game.provisional}<small aria-hidden="true">vorläufig</small>{/if}
      </div>
    {/if}
    {#if metaText}<div class="dss-sg-meta">{metaText}</div>{/if}
    {#if game.note}<div class="dss-sch-note">{game.note}</div>{/if}
    {#if notice}{@render notice(game)}{/if}
  </div>
{/snippet}

<div class="dss-frame {klass}">
  {#if title || meta}
    <div class="dss-frame-head">
      {#if title}<h3 class="dss-frame-title">{title}</h3>{:else}<span></span>{/if}
      <div class="dss-frame-meta">{#if meta}<span>{meta}</span>{/if}</div>
    </div>
  {/if}
  <div class="dss-table-scroll">
    <!-- svelte-ignore a11y_no_redundant_roles -->
    <table role="table" class="dss-tbl dss-sgrid dss-tbl--{density}">
      {#if caption}<caption class="dss-sr-only">{caption}</caption>{/if}
      <!-- svelte-ignore a11y_no_redundant_roles -->
      <thead role="rowgroup">
        <!-- svelte-ignore a11y_no_redundant_roles -->
        <tr role="row">
          <th scope="col" role="columnheader" class="dss-sg-time">Zeit</th>
          {#each columns as column (column.id)}
            <th scope="col" role="columnheader">{column.label}</th>
          {/each}
        </tr>
      </thead>
      <!-- svelte-ignore a11y_no_redundant_roles -->
      <tbody role="rowgroup">
        {#each rows as row, index (`${row.kind}-${row.time ?? ''}-${index}`)}
          {#if row.kind === 'break'}
            <!-- svelte-ignore a11y_no_redundant_roles -->
            <tr role="row" class="dss-sg-break">
              <th scope="row" role="rowheader" class="dss-sg-time">{row.time}</th>
              <td role="cell" colspan={columns.length}>{row.label}</td>
            </tr>
          {:else if row.kind === 'bye'}
            <!-- svelte-ignore a11y_no_redundant_roles -->
            <tr role="row" class="dss-sg-bye">
              <th scope="row" role="rowheader" class="dss-sg-time">{row.time ?? ''}</th>
              <td role="cell" colspan={columns.length}>{row.game.heim ? `${row.game.heim.name} hat Freilos` : (row.game.note ?? 'Spielfrei')}</td>
            </tr>
          {:else}
            <!-- svelte-ignore a11y_no_redundant_roles -->
            <tr role="row">
              <th scope="row" role="rowheader" class="dss-sg-time">{row.time}</th>
              {#each row.cells as cell, columnIndex (columns[columnIndex].id)}
                <td role="cell" class="dss-sg-cell" class:is-empty={cell.length === 0} data-label={columns[columnIndex].label}>
                  {#if cell.length === 0}
                    <span class="dss-sg-empty">{emptyLabel}</span>
                  {:else}
                    {#each cell as game (game.id)}{@render gameBlock(game)}{/each}
                  {/if}
                </td>
              {/each}
            </tr>
          {/if}
        {/each}
      </tbody>
    </table>
  </div>
</div>
