// react/Skeleton.tsx
import type { CSSProperties } from 'react';
import { cn } from './cn';

export type SkeletonVariant = 'line' | 'block' | 'circle' | 'row' | 'match';

export interface SkeletonProps {
  variant?: SkeletonVariant;
  width?: string;
  height?: string;
  /** Eckenradius (ignoriert beim Kreis). */
  rounded?: string;
  /** Anzahl der Wiederholungen (nicht bei `match`). */
  count?: number;
  /** Text für Screenreader, wird einmal angesagt. */
  label?: string;
  className?: string;
}

function Bar({ style, circle }: { style: CSSProperties; circle?: boolean }) {
  return <div className={cn('dss-skel', circle ? 'dss-skel--circle' : 'dss-skel--line')} style={style} aria-hidden="true" />;
}

/** Shimmer-Platzhalter für Ladezustände; die Platzhalter sind dekorativ, ein einzelner Status-Text meldet das Laden. */
export function Skeleton({
  variant = 'line',
  width = 'auto',
  height = 'auto',
  rounded = '6px',
  count = 1,
  label = 'Lädt …',
  className,
}: SkeletonProps) {
  const status = (
    <span role="status" className="dss-sr-only">
      {label}
    </span>
  );

  if (variant === 'row') {
    return (
      <>
        {Array.from({ length: count }, (_, i) => (
          <div key={i} className={cn('dss-skel-row', className)} aria-hidden="true">
            <Bar circle style={{ width: 44, height: 44 }} />
            <div className="dss-skel-who">
              <Bar style={{ width: '50%', height: 14 }} />
              <Bar style={{ width: '30%', height: 10, marginTop: 4 }} />
            </div>
            <Bar style={{ width: 60, height: 18 }} />
          </div>
        ))}
        {status}
      </>
    );
  }

  if (variant === 'match') {
    return (
      <>
        <div className={cn('dss-skel-match', className)} aria-hidden="true">
          <div className="dss-skel-match-head">
            <Bar style={{ width: 90, height: 10 }} />
            <Bar style={{ width: 70, height: 10 }} />
          </div>
          {[0, 1].map((row) => (
            <div key={row} className="dss-skel-match-row">
              <Bar circle style={{ width: 12, height: 12 }} />
              <Bar style={{ flex: 1, height: 18 }} />
              <Bar style={{ width: 36, height: 22 }} />
            </div>
          ))}
        </div>
        {status}
      </>
    );
  }

  return (
    <>
      {Array.from({ length: count }, (_, i) => (
        <div
          key={i}
          className={cn('dss-skel', `dss-skel--${variant}`, className)}
          style={{ width, height, borderRadius: variant === 'circle' ? '50%' : rounded }}
          aria-hidden="true"
        />
      ))}
      {status}
    </>
  );
}

// svelte/Skeleton.svelte
<script lang="ts">
  /**
   * DSS Skeleton · Svelte 5
   * --------------------------------------------------------------
   * Shimmer-Platzhalter für Ladezustände; Größen entsprechen dem späteren Inhalt.
   * Nutzt nur Klassen aus css/components.css. Die Platzhalter sind dekorativ
   * (aria-hidden), ein einzelner Status-Text (`label`) meldet das Laden.
   *
   *   line   — Textzeile (width passend zur echten Überschrift)
   *   block  — Rechteck (Karten, Bilder)
   *   circle — Avatar / Trikot
   *   row    — fertige Spieler-Zeile
   *   match  — fertige Spielkarte
   */
  let {
    variant = 'line',
    width = 'auto',
    height = 'auto',
    rounded = '6px',
    count = 1,
    label = 'Lädt …',
  }: {
    variant?: 'line' | 'block' | 'circle' | 'row' | 'match';
    width?: string;
    height?: string;
    rounded?: string;
    count?: number;
    label?: string;
  } = $props();
</script>

{#if variant === 'row'}
  {#each Array(count) as _, i (i)}
    <div class="dss-skel-row" aria-hidden="true">
      <div class="dss-skel dss-skel--circle" style="width: 44px; height: 44px;"></div>
      <div class="dss-skel-who">
        <div class="dss-skel dss-skel--line" style="width: 50%; height: 14px;"></div>
        <div class="dss-skel dss-skel--line" style="width: 30%; height: 10px; margin-top: 4px;"></div>
      </div>
      <div class="dss-skel dss-skel--line" style="width: 60px; height: 18px;"></div>
    </div>
  {/each}
{:else if variant === 'match'}
  <div class="dss-skel-match" aria-hidden="true">
    <div class="dss-skel-match-head">
      <div class="dss-skel dss-skel--line" style="width: 90px; height: 10px;"></div>
      <div class="dss-skel dss-skel--line" style="width: 70px; height: 10px;"></div>
    </div>
    {#each [0, 1] as row (row)}
      <div class="dss-skel-match-row">
        <div class="dss-skel dss-skel--circle" style="width: 12px; height: 12px;"></div>
        <div class="dss-skel dss-skel--line" style="flex: 1; height: 18px;"></div>
        <div class="dss-skel dss-skel--line" style="width: 36px; height: 22px;"></div>
      </div>
    {/each}
  </div>
{:else}
  {#each Array(count) as _, i (i)}
    <div
      class={`dss-skel dss-skel--${variant}`}
      style={`width: ${width}; height: ${height}; border-radius: ${variant === 'circle' ? '50%' : rounded};`}
      aria-hidden="true"
    ></div>
  {/each}
{/if}
<span role="status" class="dss-sr-only">{label}</span>
