// react/Tabs.tsx
import { useRef, useState, type KeyboardEvent } from 'react';
import { Icon, type IconName } from './Icon';
import { cn } from './cn';

export interface TabItem {
  id: string;
  label: string;
  icon?: IconName;
  count?: number;
  disabled?: boolean;
}

export type TabsVariant = 'underline' | 'segmented' | 'pills' | 'vertical';
export type TabsSize = 'sm' | 'md' | 'lg';

export interface TabsProps {
  items: TabItem[];
  variant?: TabsVariant;
  size?: TabsSize;
  ariaLabel?: string;
  className?: string;
  /** Einzelauswahl: kontrolliert (value) oder unkontrolliert (defaultValue). */
  value?: string;
  defaultValue?: string;
  onValueChange?: (id: string) => void;
  /** Mehrfachauswahl (Pills als Filter): kontrolliert (activeIds) oder unkontrolliert. */
  multi?: boolean;
  activeIds?: string[];
  defaultActiveIds?: string[];
  onActiveIdsChange?: (ids: string[]) => void;
}

export function Tabs({
  items,
  variant = 'underline',
  size = 'md',
  ariaLabel = 'Tabs',
  className,
  value: valueProp,
  defaultValue,
  onValueChange,
  multi = false,
  activeIds: activeIdsProp,
  defaultActiveIds = [],
  onActiveIdsChange,
}: TabsProps) {
  const firstEnabled = items.find((item) => !item.disabled)?.id ?? '';
  const [innerValue, setInnerValue] = useState(defaultValue ?? firstEnabled);
  const [innerActiveIds, setInnerActiveIds] = useState(defaultActiveIds);
  const buttons = useRef<Array<HTMLButtonElement | null>>([]);

  const value = valueProp ?? innerValue;
  const activeIds = activeIdsProp ?? innerActiveIds;
  const isActive = (id: string) => (multi ? activeIds.includes(id) : value === id);

  const select = (item: TabItem) => {
    if (item.disabled) return;
    if (multi) {
      const next = activeIds.includes(item.id) ? activeIds.filter((id) => id !== item.id) : [...activeIds, item.id];
      setInnerActiveIds(next);
      onActiveIdsChange?.(next);
    } else {
      setInnerValue(item.id);
      onValueChange?.(item.id);
    }
  };

  const onKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number) => {
    if (multi) return;
    const horizontal = variant !== 'vertical';
    const nextKey = horizontal ? 'ArrowRight' : 'ArrowDown';
    const prevKey = horizontal ? 'ArrowLeft' : 'ArrowUp';
    if (event.key !== nextKey && event.key !== prevKey) return;

    event.preventDefault();
    const direction = event.key === nextKey ? 1 : -1;
    let next = index;
    for (let i = 0; i < items.length; i++) {
      next = (next + direction + items.length) % items.length;
      if (!items[next].disabled) break;
    }
    select(items[next]);
    buttons.current[next]?.focus();
  };

  return (
    <div
      className={cn('dss-tabs', `dss-tabs--${variant}`, `dss-tabs--${size}`, className)}
      role={multi ? 'group' : 'tablist'}
      aria-label={ariaLabel}
      aria-orientation={!multi && variant === 'vertical' ? 'vertical' : undefined}
    >
      {items.map((item, index) => {
        const active = isActive(item.id);
        return (
          <button
            key={item.id}
            ref={(el) => {
              buttons.current[index] = el;
            }}
            type="button"
            className={cn('dss-tab', active && 'is-active', item.disabled && 'is-disabled')}
            role={multi ? undefined : 'tab'}
            aria-selected={multi ? undefined : active}
            aria-pressed={multi ? active : undefined}
            disabled={item.disabled}
            tabIndex={multi ? undefined : active ? 0 : -1}
            onClick={() => select(item)}
            onKeyDown={(event) => onKeyDown(event, index)}
          >
            {item.icon ? <Icon name={item.icon} size={16} className="dss-tab-ic" /> : null}
            <span className="dss-tab-label">{item.label}</span>
            {item.count !== undefined ? <span className="dss-tab-count">{item.count}</span> : null}
          </button>
        );
      })}
    </div>
  );
}

// svelte/Tabs.svelte
<script lang="ts">
  /**
   * DSS Tabs · Svelte 5 example
   * --------------------------------------------------------------
   * Matches the v0.6 Navigation spec — four variants:
   *
   *   underline  — page tabs, sticky-safe (default)
   *   segmented  — single-pick toggle with shared track
   *   pills      — wrap-friendly filter chips (multi-active possible)
   *   vertical   — sidebar-style tabs (settings pages)
   *
   * Usage:
   *   <Tabs bind:value={tab} variant="underline" items={[
   *     { id: 'overview', label: 'Übersicht', icon: 'i-board' },
   *     { id: 'roster',   label: 'Aufstellung', count: 12 },
   *     { id: 'box',      label: 'Boxscore' },
   *   ]} />
   *
   * Nutzt ausschließlich die Klassen aus css/components.css (kein eigener Scoped-Style);
   * tokens.css und components.css müssen im App-Root importiert sein.
   * Icons referenced via `icon` are <use href="#i-…">; sprite must be
   * loaded in the page (or use the Icon.svelte component to inline).
   */

  type TabItem = {
    id: string;
    label: string;
    icon?: string;     // sprite id, e.g. 'i-board'  (without the '#')
    count?: number;    // optional badge
    disabled?: boolean;
  };

  type Variant = 'underline' | 'segmented' | 'pills' | 'vertical';
  type Size = 'sm' | 'md' | 'lg';

  let {
    items,
    value = $bindable(''),
    variant = 'underline',
    size = 'md',
    multi = false,         // pills can toggle multi-select
    activeIds = $bindable<string[]>([]),
    ariaLabel = 'Tabs',
    onchange,
  }: {
    items: TabItem[];
    value?: string;
    variant?: Variant;
    size?: Size;
    multi?: boolean;
    activeIds?: string[];
    ariaLabel?: string;
    onchange?: (id: string) => void;
  } = $props();

  // Initialise value to the first item if not provided.
  $effect(() => {
    if (!multi && !value && items.length) value = items[0].id;
  });

  function isActive(id: string) {
    return multi ? activeIds.includes(id) : value === id;
  }

  function select(item: TabItem) {
    if (item.disabled) return;
    if (multi) {
      activeIds = activeIds.includes(item.id)
        ? activeIds.filter(x => x !== item.id)
        : [...activeIds, item.id];
    } else {
      value = item.id;
    }
    onchange?.(item.id);
  }

  function onKey(e: KeyboardEvent, idx: number) {
    const isHoriz = variant !== 'vertical';
    const nextKey = isHoriz ? 'ArrowRight' : 'ArrowDown';
    const prevKey = isHoriz ? 'ArrowLeft'  : 'ArrowUp';
    if (e.key === nextKey || e.key === prevKey) {
      e.preventDefault();
      const dir = e.key === nextKey ? 1 : -1;
      let n = idx;
      for (let i = 0; i < items.length; i++) {
        n = (n + dir + items.length) % items.length;
        if (!items[n].disabled) break;
      }
      select(items[n]);
      // refocus
      const btns = (e.currentTarget as HTMLElement).parentElement?.querySelectorAll<HTMLButtonElement>('button.dss-tab');
      btns?.[n]?.focus();
    }
  }
</script>

<div
  class="dss-tabs dss-tabs--{variant} dss-tabs--{size}"
  role={multi ? 'group' : 'tablist'}
  aria-label={ariaLabel}
  aria-orientation={variant === 'vertical' ? 'vertical' : 'horizontal'}
>
  {#each items as item, i (item.id)}
    <button
      type="button"
      class="dss-tab"
      class:is-active={isActive(item.id)}
      class:is-disabled={item.disabled}
      role={multi ? undefined : 'tab'}
      aria-selected={multi ? undefined : isActive(item.id)}
      aria-pressed={multi ? isActive(item.id) : undefined}
      disabled={item.disabled}
      tabindex={isActive(item.id) ? 0 : -1}
      onclick={() => select(item)}
      onkeydown={(e) => onKey(e, i)}
    >
      {#if item.icon}
        <svg class="dss-tab-ic" width="16" height="16" viewBox="0 0 24 24" aria-hidden="true">
          <use href={`#${item.icon}`}></use>
        </svg>
      {/if}
      <span class="dss-tab-label">{item.label}</span>
      {#if item.count !== undefined}
        <span class="dss-tab-count">{item.count}</span>
      {/if}
    </button>
  {/each}
</div>
