// react/TopBar.tsx
import type { ReactNode } from 'react';
import { cn } from './cn';

export type TopBarContext = 'default' | 'live' | 'admin';

export interface TopBarProps {
  brand?: string;
  /** Kurzzeichen im Amber-Quadrat (dekorativ). */
  mark?: string;
  context?: TopBarContext;
  matchLabel?: string;
  score?: string;
  clock?: string;
  user?: string;
  userInitials?: string;
  leading?: ReactNode;
  center?: ReactNode;
  actions?: ReactNode;
  /** `header` macht die Leiste zur banner-Landmark (Standard: div). */
  as?: 'header' | 'div';
  /** Begrenzt den Inhalt auf `--dss-shell-max` (Hintergrund bleibt voll breit). */
  contained?: boolean;
  className?: string;
}

/** Dunkle App-Leiste (56 px): Marke links, optionaler Spielkontext, Aktionen rechts. */
export function TopBar({
  brand = 'DSS',
  mark = 'D',
  context = 'default',
  matchLabel = '',
  score = '',
  clock = '',
  user = '',
  userInitials = '',
  leading,
  center,
  actions,
  as: Root = 'div',
  contained = false,
  className,
}: TopBarProps) {
  return (
    <Root className={cn('dss-topbar', 'dss-topbar--dark', contained && 'dss-topbar--contained', className)}>
      <div className="dss-topbar-brand">
        <span className="dss-topbar-mark" aria-hidden="true">
          {mark}
        </span>
        {brand}
      </div>

      {leading}

      {center ? (
        <div className="dss-topbar-center">{center}</div>
      ) : context === 'live' ? (
        <div className="dss-topbar-ctx">
          <span className="dss-topbar-live">Live</span>
          {matchLabel ? <span>{matchLabel}</span> : null}
          {score ? <span className="dss-topbar-score">{score}</span> : null}
          {clock ? <span className="dss-topbar-clock">{clock}</span> : null}
        </div>
      ) : context === 'admin' && matchLabel ? (
        <div className="dss-topbar-ctx">
          <span>{matchLabel}</span>
        </div>
      ) : null}

      <span className="dss-topbar-spacer" />

      {actions}

      {user ? (
        <div className="dss-topbar-user">
          {userInitials ? <span className="dss-topbar-av">{userInitials}</span> : null}
          {user}
        </div>
      ) : null}
    </Root>
  );
}

// svelte/TopBar.svelte
<script lang="ts">
  /**
   * DSS TopBar · Svelte 5
   * --------------------------------------------------------------
   * App-Shell-Leiste, dunkle Fläche, 56 px. Marke links, optionaler
   * Spielkontext, Aktionen rechts. Nutzt nur Klassen aus css/components.css
   * (`dss-topbar dss-topbar--dark`; die helle `.dss-topbar` bleibt dem
   * Vereinsregister).
   *
   *   default — ruhig, ohne Live-Anzeige
   *   live    — grüner Puls + Spielstand + Uhr (Schiri-/Coach-App)
   *   admin   — Breadcrumb-Kontext (Vereinsregister, Einstellungen)
   */
  import type { Snippet } from 'svelte';

  let {
    brand = 'DSS',
    mark = 'D',
    context = 'default',
    matchLabel = '',
    score = '',
    clock = '',
    user = '',
    userInitials = '',
    leading,
    center,
    actions,
    contained = false,
  }: {
    brand?: string;
    mark?: string;
    context?: 'default' | 'live' | 'admin';
    matchLabel?: string;
    score?: string;
    clock?: string;
    user?: string;
    userInitials?: string;
    leading?: Snippet;
    center?: Snippet;
    actions?: Snippet;
    /** Begrenzt den Inhalt auf `--dss-shell-max` (Hintergrund bleibt voll breit). */
    contained?: boolean;
  } = $props();
</script>

<div class="dss-topbar dss-topbar--dark" class:dss-topbar--contained={contained}>
  <div class="dss-topbar-brand">
    <span class="dss-topbar-mark" aria-hidden="true">{mark}</span>
    {brand}
  </div>

  {#if leading}{@render leading()}{/if}

  {#if center}
    <div class="dss-topbar-center">{@render center()}</div>
  {:else if context === 'live'}
    <div class="dss-topbar-ctx">
      <span class="dss-topbar-live">Live</span>
      {#if matchLabel}<span>{matchLabel}</span>{/if}
      {#if score}<span class="dss-topbar-score">{score}</span>{/if}
      {#if clock}<span class="dss-topbar-clock">{clock}</span>{/if}
    </div>
  {:else if context === 'admin' && matchLabel}
    <div class="dss-topbar-ctx">
      <span>{matchLabel}</span>
    </div>
  {/if}

  <span class="dss-topbar-spacer"></span>

  {#if actions}{@render actions()}{/if}

  {#if user}
    <div class="dss-topbar-user">
      {#if userInitials}<span class="dss-topbar-av">{userInitials}</span>{/if}
      {user}
    </div>
  {/if}
</div>
